### ISSUE TITLE
RoleAssignmentUpdateNotPermitted

### ISSUE THREAD

**Issue by rootomatic** [microsoft/startstopv2-deployments#10]
Deployment fails with the following error
Account used was subscription owner

Microsoft.Authorization/roleAssignments

```
{
    "status": "Failed",
    "error": {
        "code": "RoleAssignmentUpdateNotPermitted",
        "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
}
```

**Comment by parojasmsft** [comment]
Hi Rootomatic,
I will have our dev team look into this. Please stand by.

**Comment by balas77** [comment]
Hi rootomatic - Can you please check whether you have any internal policy that has been configured at the subscription level which is preventing to do the roleAssignments? In the deployment workflow the roleAssignments will be performed as the last step so you should have seen the V2 components (RG, Function app, Logic apps, Dashboard etc) already got created. The final step would perform the action of adding the function app managed identity as "**contributor**" role at the subscription level. Can you please try to see if you can perform that step manually?

**Comment by rootomatic** [comment]
Thanks for the response. I was able to manually add the role assignment using the same account I attempted to deploy the solution with

**Comment by balas77** [comment]
Glad to know that it worked but curious to understand why it didnt worked from the ARM template deployment since we havent received any tickets regarding this issue. Would you be able to share some addition error details and the subscription details via to our email aoateamo@microsoft.com?

**Comment by balas77** [comment]
Hi rootomatic - I am going ahead and closing this ticket now. As mentioned above please reach us and do share the details which will be helpful for us to troubleshoot this one off issue. Thank you again for using Start/Stop V2!
