### ISSUE TITLE
Deployment using Classic Application Insight

### ISSUE THREAD

**Issue by rikunarhi-cloud2** [microsoft/startstopv2-deployments#106]
The deployment is using Classic Application Insights which will be retired on 29.02.2024. 

Is there a plan to transsition to using workspace-based application insights?

**Comment by HungZy95** [comment]
Hello guys,

Any updates on this one?

The Classic Application Insights will be depreciated in a month + few days.
I'm afraid that this will affect our services since StartStopVM can stop working afterwards.

**Comment by jeffw16** [comment]
We rolled out an update in February to move to workspace-based Application Insights. Automatic upgrades should have rolled out for everyone. In case you are encountering an issue, please read the official guidance on the following issue: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492
