### ISSUE TITLE
SSV2_AutomationUpdateGA

### ISSUE THREAD

**Issue by kik123and** [microsoft/startstopv2-deployments#112]
After automatic Azure update or something - "Deployment name: SSV2_AutomationUpdateGA", Function app associated with Logical app for Start/Stop VMs v2 cannot be started anymore.

Error: Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.WebJobs.Extensions.Storage.Blobs: Could not load file or assembly 'Azure.Core, Version=1.25.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. Format of the executable (.exe) or library (.dll) is invalid. System.Private.CoreLib: Could not load file or assembly 'C:\home\site\wwwroot\bin\Azure.Core.dll'. Format of the executable (.exe) or library (.dll) is invalid.

**Comment by watchout1214** [comment]
My StartStopV2 broke sometime between 02/13/2024 and 02/14/2024.  I got the same errors as listed in the issue.  I am using the Government Cloud and have had no issues with the StartStopV2 tool until the 14th.  I deployed a fresh version to my sandbox and still have the same errors.

Is this tool still supported or do we need to find a new solution?

Thanks,

**Comment by FirstFlapjack** [comment]
Here too. Working perfectly (twice daily) for a couple of months....then the last success was 14/02/2024.

Inside the function app "StartStopVM_____" there are 2 notifications:

AZFD0005 Error configuring services in an external startup class.
....and....
Functions runtime error 
Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.WebJobs.Extensions.Tables: Could not load file or assembly 'Microsoft.Extensions.Azure, Version=1.7.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. The system cannot find the file specified.

**Comment by watchout1214** [comment]
I opened a support case for this issue.  I will report back when I get updates.  I was told that this solution is still supported.

**Comment by watchout1214** [comment]
Worked with MS on the problem.  Solution is to stop your Function App first.  Then, redeploy the app from the GitHub link and make sure to provide the same parameter values so that the template only updates the Function App.  It sounds like there can be issues with the autoupdate feature if the Function App is up and running when the update occurs.

Stopping the Function App and then doing the redeploy from the GitHub did fix my issue and all is well again.

HTH

**Comment by jeffw16** [comment]
Thank you all for providing detailed information for the community! Here is the official guidance: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492
