### ISSUE TITLE
Guidance on deployment or migration to isolated worker model

### ISSUE THREAD

**Issue by lmf-mx** [microsoft/startstopv2-deployments#114]
Emails were sent for Functions use in-process model instead of isolated workers. What needs to be done to update this solution once deployed or deploy using the other model?

There appear to be a number of changes per https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=netframework48 required in the code.

Looking for guidance or timeframe expectation when we will have guidance on migration or new deployment option.

**Comment by lmf-mx** [comment]
I guess we should throw in the earlier deadline to move from .NET 6 to 8 as well. https://learn.microsoft.com/en-us/azure/azure-functions/update-language-versions?pivots=programming-language-csharp

**Comment by frontegi** [comment]
Hi, I received and Alert directly from Azure Health, requesting me to upgrade my own developed Functions to .Net 8 and isolated  process model. So I expect that Azure Team is going to upgrade this repo or the Auto-Update feature of Start Stop solution.
So, I'm adding a +1 to this issue.

**Comment by Lauwnch** [comment]
I am also looking for information on performing this upgrade, or whether the Azure team will be taking care of it.

**Comment by jeffw16** [comment]
We will imminently release a new version of StartStop V2 that moves to .NET 8 and uses the isolated worker model. We thank everyone for their patience.
