### ISSUE TITLE
Error 404 not found

### ISSUE THREAD

**Issue by FabioBrianzaSistemi** [microsoft/startstopv2-deployments#118]
Hello,

since a couple of weeks, with no changes on the configuration, my Start/Stop VMs v2 script goes on error 404 resource not found when trying to start the virtual machine.

The subscription ID is correct, and there is only one VM in the subscription.

I'm in the Function-Try step, with the following code:

```
{
    "function": {
        "name": "StartStopV2krk73u3tu4ozm/Scheduled",
        "id": "/subscriptions/MYSUBSCRIPTIONID/resourceGroups/RESOURCEGROUP/providers/Microsoft.Web/sites/StartStopV2krk73u3tu4ozm/functions/Scheduled",
        "type": "Microsoft.Web/sites/functions"
    },
    "body": {
        "Action": "start",
        "EnableClassic": false,
        "RequestScopes": {
            "ExcludedVMLists": [],
            "Subscriptions": [
                "/subscriptions/MYSUBSCRIPTIONID/"
            ]
        }
    }
}
```

(where MYSUBSCRIPTIONID is my number c61...-....-....-....-....... and RESOURCEGROUP is the resource group name)

The output says 
```
{
    "statusCode": 404,
    "headers": {
        "Date": "Thu, 13 Jun 2024 05:15:02 GMT",
        "Request-Context": "appId=cid-v1:285f25a8-8630-40d1-a38d-aab9e9978435",
        "X-Content-Type-Options": "nosniff",
        "Content-Length": "0"
    }
}
```

Any suggestion on how to fix it?

Thank you,

Fabio

**Comment by JohnLBevan** [comment]
FYI: We've started seeing the same issue this morning.
Looking at the hosting function app's activity log we see that there was an `UpdateWebSite` event before these issues began.
The change history tab of that event shows the following:

| Changed Property | Change Type | Change Category | Old Value | New Value |
| -- | -- | -- | -- | -- |
| properties.appSettings["CentralizedLoggingOptions:Version"].value | Update | User | 1.1.20240422.1 | 1.1.20240617.1 |
| properties.appSettings["AzureClientOptions:AutoUpdateTemplateUri"].value | Update | User | https://startstopv2prod.blob.core.windows.net/artifacts/ssv2autoupdate.json | https://raw.githubusercontent.com/microsoft/startstopv2-deployments/main/artifacts/ssv2autoupdate.json |
| properties.appSettings["AzureClientOptions:AutoUpdateRegionsUri"].value | Update | User | https://startstopv2prod.blob.core.windows.net/artifacts/AutoUpdateRegionsGA.json | https://raw.githubusercontent.com/microsoft/startstopv2-deployments/main/artifacts/AutoUpdateRegionsGA.json |
| properties.appSettings["AzureClientOptions:Version"].value | Update | User | 1.1.20240422.1 | 1.1.20240617.1 | 


NB: We've also seen oddities in other start-stop function apps which MS have upgraded in the background, where the `HeartBeatAvailabilityTest` causes `List Web Apps Functions Host Keys` to show in the function app's event log 3 times every time it's run (i.e. every 5 mins).  For those, the update event's change history shows the same versions as above; i.e.

| Changed Property | Change Type | Change Category | Old Value | New Value |
| -- | -- | -- | -- | -- |
| properties.appSettings["CentralizedLoggingOptions:Version"].value | Update | User | 1.1.20240422.1 | 1.1.20240617.1 |
| properties.appSettings["AzureClientOptions:AutoUpdateTemplateUri"].value | Update | User | https://startstopv2prod.blob.core.windows.net/artifacts/ssv2autoupdate.json | https://raw.githubusercontent.com/microsoft/startstopv2-deployments/main/artifacts/ssv2autoupdate.json |
| properties.appSettings["AzureClientOptions:AutoUpdateRegionsUri"].value | Update | User | https://startstopv2prod.blob.core.windows.net/artifacts/AutoUpdateRegionsGA.json | https://raw.githubusercontent.com/microsoft/startstopv2-deployments/main/artifacts/AutoUpdateRegionsGA.json |
| properties.appSettings["AzureClientOptions:Version"].value | Update | User | 1.1.20240422.1 | 1.1.20240617.1 |

**Comment by JohnLBevan** [comment]
NB: This may be the same issue; the reported symptom there being based on notifications whilst here it's based on logs.
#122 
That includes a comment on how to resolve the issue (i.e. by redeploying the function): https://github.com/microsoft/startstopv2-deployments/issues/112#issuecomment-1961755579

**Comment by FabioBrianzaSistemi** [comment]
I confirm that the comment of @JohnLBevan solves the issue, it's the same issue as [#122 ](https://github.com/microsoft/startstopv2-deployments/issues/112#issuecomment-1961755579) with a different error code. Thank you!

**Comment by jeffw16** [comment]
Thank you all for providing your inputs. Please see the official guidance on the following issue: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492
