### ISSUE TITLE
StartStopV2_Dashboard

### ISSUE THREAD

**Issue by schottky81** [microsoft/startstopv2-deployments#12]
Hello,

I have tried to open the provided dashboard but there's no data returned.
There are logs under "traces" but the query is formed with the following where condition: 
customDimensions.prop__Name == "VmExecutionsAttempted"
This does not return any result.
Has anyone been able to display data in a dashboard for StartStopV2 so far?

**Comment by parojasmsft** [comment]
Hi @schottky81
I will let the dev team know there is an issue with the dashboard. Please email your contact information to startstopv2team@microsoft.com so we can work directly with you.

**Comment by balas77** [comment]
@schottky81 Just checking back with you on this. As mentioned by our team, did you get a chance to enable the start and stop schedules to make sure you get the report part working?

**Comment by nk2303** [comment]
@schottky81 Hello, I will close this issue.

**Comment by nk2303** [comment]
Hi @schottky81 , we will close this issue.

**Comment by schottky81** [comment]
Hello,

Sorry for the late reply. I have checked on the subscription and schedules
have been set up from the beginning. I wonder why there is no data in the
dashboard.
[image: image.png]

Regards,
Raphaël

**Comment by sccjas** [comment]
We have several stop/start events but only see data in 2 widgets - "Recently attempted actions on VMs" and "Count by Resource Group"

**Comment by balas77** [comment]
Thanks for getting back on this. For some reason we cant see your screenshot here so it would be better if you can share the screenshot to our email directly (aoateamo@microsoft.com)
I do have some suspect on the dashboard query's property name. Can you guys follow the below steps to update the existing dashboard query? This will help to isolate the issue.

1. Navigate to the StartStopV2_Dashboard and choose the tile where you don't get the report rendered.
2. Click on the edit icon on the tile (for example on the 2nd tile **Successful Start and Stop Actions Taken** where you can see the report **not** rendered)
 
![image](https://user-images.githubusercontent.com/64924532/126546477-7c55f377-ab76-4668-9a59-88f9074157e3.png)
  
![image](https://user-images.githubusercontent.com/64924532/126546184-4d808073-17e2-40b5-8178-77ac67c68b1e.png)
3. This should open up the query window. Change the customDimensions.prop_value --> customDimensions.prop_**V**alue (changing the value to uppercase V, but if you already have uppercase V then make sure to change it to lowercase v)
![image](https://user-images.githubusercontent.com/64924532/126547857-be6fa573-2229-40f4-a04c-9067309042c3.png)

4. Click Run . You should see the report which rendered correctly as below.
![image](https://user-images.githubusercontent.com/64924532/126547211-72fb791f-c347-4dab-870d-b795cef8941e.png)
 
5. Click Apply & Save the dashboard.

![image](https://user-images.githubusercontent.com/64924532/126547478-5db23431-effb-46a8-a025-934c195f4ede.png)

Please do let me know on the outcome and if this doesn't resolve the problem then we should get in the call to troubleshoot further.

**Comment by sccjas** [comment]
changing "value" to "Value" fixed the issue.  All my widgets have data now. Thanks.

**Comment by sccjas** [comment]
We run into another issue when adding systems to the Logic App.  We added a system to Stop Logic App, few minutes after saving the Logic Apps the test VM stopped. After adding the same VM to the start logic app, the VM starts upon saving the logic app changes.  Looks like the app triggers the action when the VM is first added to the logic app.

**Comment by balas77** [comment]
@sccjas - Great to hear that it works 👍 

@schottky81 - Can you please check and let me know if this works for you as well?

**Comment by schottky81** [comment]
Thanks for the update.
I have tried to update the query for "Successful Start and Stop Actions
Taken" by replacing "prop__value" with "prop__Value" without any success.
No data is returned as you can see in my print screens.
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by balas77** [comment]
@schottky81 - Sorry to hear that this isn't working for you. I would like to setup quick teams meeting with you so can you please share your email id and your working timezone to aoateamo@microsoft.com? I will setup the meeting to discuss/troubleshoot this.

**Comment by schottky81** [comment]
Hello,

Thank you for the proposition but you can close the issue for now even if
it is not solved for us.

**Comment by balas77** [comment]
Sure. In future if you need any help on this please do reach us!
