### ISSUE TITLE
Error configuring services in an external startup class.

### ISSUE THREAD

**Issue by antonioguirola** [microsoft/startstopv2-deployments#122]
The Azure Function has been working fine the last months until this morning (19/6/2024) when we have started to get this errors:

![image](https://github.com/microsoft/startstopv2-deployments/assets/5548751/e0aa7600-d5f3-4148-a31a-dd9b86407ff1)

Exception detail:

Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. StartStopAzureFunctions: Could not load file or assembly 'Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc'. Format of the executable (.exe) or library (.dll) is invalid. System.Private.CoreLib: Could not load file or assembly 'C:\home\site\wwwroot\bin\Polly.dll'. Format of the executable (.exe) or library (.dll) is invalid.

Thank You.

**Comment by jeffw16** [comment]
Thank you all for providing your inputs. Please see the official guidance on the following issue: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492
