### ISSUE TITLE
[Enhancement] Add hibernation as a stop option

### ISSUE THREAD

**Issue by psilantropy** [microsoft/startstopv2-deployments#127]
https://learn.microsoft.com/en-us/azure/virtual-machines/hibernate-resume

Hibernation is in GA. Would be nice to have this as an option to VM owners instead of just stop.

**Comment by jeffw16** [comment]
Thank you for taking the time to provide this suggestion. StartStop V2 is no longer being actively developed. In case this changes in the future, we will be sure to consider your enhancement idea.
