### ISSUE TITLE
Microsoft Support

### ISSUE THREAD

**Issue by abhiramani-git** [microsoft/startstopv2-deployments#128]
Hi
how do we reach microsoft support for this solution? i mean which all drop downs do we select? i created few tickets either selected VM or Logic App and they all redirect me to our microsoft rep

THis is what support page says:
If you run into problems during deployment, you encounter an issue when using Start/Stop VMs v2, or if you have a related question, you can submit an issue on [GitHub](https://github.com/microsoft/startstopv2-deployments/issues). Filing an Azure support incident from the [Azure support site](https://azure.microsoft.com/support/options/) is also available for this version.

**Comment by jeffw16** [comment]
Your Microsoft representative should be able to point you to the right place.
