### ISSUE TITLE
Logic App shutdown the VM right after adding the VM to the Logic App

### ISSUE THREAD

**Issue by sccjas** [microsoft/startstopv2-deployments#13]
We run into another issue when adding systems to the Logic App. We added a system to Stop Logic App, few minutes after saving the Logic Apps the test VM stopped. After adding the same VM to the start logic app, the VM starts upon saving the logic app changes. Looks like the app triggers the action when the VM is first added to the logic app.

We added the VM in the afternoon and the Shutdown schedule is 7pm.   Otherwise, the Stop/Start works according to the schedule.

**Comment by balas77** [comment]
Hi - This is known/default behavior of the Logic apps which triggers only for the **first time** when you enable the logic apps which is basically needed to determine the current & next run hence the behavior.

**Comment by sccjas** [comment]
Thanks for the prompt response.  This is a usability issue.   Can't the function retrieve the VM state without actually execute the action?  The Logic App (in Azure Commercial) built-in VM connector does not have this limitation or issue.  If a list of VMs are added then they would all reboot at the same time and catch people by surprise.

**Comment by balas77** [comment]
Ideally the **first time trigger** is for logic apps only to determine the next schedule run and this is nothing to do with VM state. All we're doing inside the logic app is to call the function app with payload. Yeah agreed and probably will add a note in the documentation on this default first time execution.

**Comment by sccjas** [comment]
We are done testing the app in our test subscription.  To move this into production, can we move the resources to our production subscription under the same Azure tenant?

**Comment by balas77** [comment]
@sccjas - Glad to know that it worked in your test subscription 👍 

Our best practice is to deploy new instance of our Start/Stop V2 in your production subscription so that you can keep/manage test & prod separately. 

But you can also certainly move all the resources under the RG from Sub1 to new RG in Sub2 but there are few manual steps that you need to preform in order the solution to work end-to-end.

1. Select all the V2 resources from the existing RG in Sub1 and click "**Move to another subscription**" option where you can define new RG in Sub2.
2. Once the move job successfully done, you have to add the function app's managed identity as "**contributor**" at the subscription level in Sub2. Follow the GitHub home page for the steps.
3. You have to update the respective function app endpoints in the Logic App.
    1. Navigate to the logic app (for example as below)
![image](https://user-images.githubusercontent.com/64924532/126826454-7b92c4a0-a6d6-422b-8def-5ce0d9402f53.png)

    2. Click on the "Logic app code view" 
![image](https://user-images.githubusercontent.com/64924532/126826561-e258db19-0694-43ea-8579-43d3d87d8dc7.png)
   3.  Update the "function id" with new subscription Id & RG name
![image](https://user-images.githubusercontent.com/64924532/126827033-ad462366-d89d-485c-8e7f-b2ccac75e23c.png)

   4.  Click Save. 
   5.  Repeat the same steps for the needed logic apps

Please let me know if this works. Thanks for using Start/Stop V2.

**Comment by balas77** [comment]
@sccjas - Forgot to tell you that our V2 solution is capable to start & stop the VMs on multi-subscription so if needed you can perform the action from your test subscription towards VMs in prod subscription. Just perform [this ](https://github.com/microsoft/startstopv2-deployments#enable-multi-subscription-support)step in production subscription and you are good to go.

**Comment by sccjas** [comment]
The resources are moved and logic apps are updated to reflect the new sub and rg.   Will see if it still works tonight.  However all the dashboard widgets are showing ‘not found’.

J

From: balas77 ***@***.***>
Date: Friday, July 23, 2021 at 11:45 AM
To: microsoft/startstopv2-deployments ***@***.***>
Cc: Yue, Jasper ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/startstopv2-deployments] Logic App shutdown the VM right after adding the VM to the Logic App (#13)

@sccjas<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sccjas&d=DwMFaQ&c=jIuf2QGe13CVwCCNhnnHSyGX0TfHadH8sr2VwRkl7n8&r=QIFgkRJr82ax2U9ZBUYtcHyq9p6UUuch3VVYW64MHUg&m=iZsS6I97iYlcwXHrlupOEYPKFsl8-7b_m-6ds2SXnds&s=05TVEsDBZrlwYNQUiaveME7GrIvu5V4CZeNSa85b9No&e=> - Glad to know that it worked in your test subscription 👍

Our best practice is to deploy new instance of our Start/Stop V2 in your production subscription so that you can keep/manage test & prod separately.

But you can also certainly move all the resources under the RG from Sub1 to new RG in Sub2 but there are few manual steps that you need to preform in order the solution to work end-to-end.

  1.  Select all the V2 resources from the existing RG in Sub1 and click "Move to another subscription" option where you can define new RG in Sub2.
  2.  Once the move job successfully done, you have to add the function app's managed identity as "contributor" at the subscription level in Sub2. Follow the GitHub home page for the steps.
  3.  You have to update the respective function app endpoints in the Logic App.
     *   Navigate to the logic app (for example as below)
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_64924532_126826454-2D7b92c4a0-2Da6d6-2D422b-2D8def-2D5ce0d9402f53.png&d=DwMFaQ&c=jIuf2QGe13CVwCCNhnnHSyGX0TfHadH8sr2VwRkl7n8&r=QIFgkRJr82ax2U9ZBUYtcHyq9p6UUuch3VVYW64MHUg&m=iZsS6I97iYlcwXHrlupOEYPKFsl8-7b_m-6ds2SXnds&s=0D77vB4Eh8x0WUpGNOxJp-OcLlhm1XVtmmtmlVBIFYw&e=>
     *   Click on the "Logic app code view"
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_64924532_126826561-2De258db19-2D0694-2D43ea-2D8579-2D43d3d87d8dc7.png&d=DwMFaQ&c=jIuf2QGe13CVwCCNhnnHSyGX0TfHadH8sr2VwRkl7n8&r=QIFgkRJr82ax2U9ZBUYtcHyq9p6UUuch3VVYW64MHUg&m=iZsS6I97iYlcwXHrlupOEYPKFsl8-7b_m-6ds2SXnds&s=oGU8DMGisknf7M4ImGOqd97A1_yExXvSmWZ7IajRnVE&e=>
     *   Update the "function id" with new subscription Id & RG name
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_64924532_126827033-2Dad462366-2Dd89d-2D485c-2D8e7f-2Db2ccac75e23c.png&d=DwMFaQ&c=jIuf2QGe13CVwCCNhnnHSyGX0TfHadH8sr2VwRkl7n8&r=QIFgkRJr82ax2U9ZBUYtcHyq9p6UUuch3VVYW64MHUg&m=iZsS6I97iYlcwXHrlupOEYPKFsl8-7b_m-6ds2SXnds&s=nADNp7sXzVUHOuvJcXisrUsCHUli3RgozcoyF1eRvR4&e=>
     *   Click Save.
     *   Repeat the same steps for the needed logic apps

Please let me know if this works. Thanks for using Start/Stop V2.

**Comment by balas77** [comment]
@sccjas - For the dashboard, you have to update it as below. There is no direct way to edit it in portal to make the changes.

1. Download the dashboard.
 
![image](https://user-images.githubusercontent.com/64924532/127227738-591588c8-f4d1-4440-ab39-93725719b611.png)

2. Edit the file in any editor. Make sure you update the subid and rgname accordingly. 
3. Upload it.
 
![image](https://user-images.githubusercontent.com/64924532/127227874-220906c6-749f-4573-a247-b1ee3bb2c955.png)

**Comment by sccjas** [comment]
Thanks

**Comment by balas77** [comment]
Hope that works for you!
