### ISSUE TITLE
programmatic deploy of marketplace-products(StopStartV2)

### ISSUE THREAD

**Issue by abhiramani-git** [microsoft/startstopv2-deployments#133]
I am trying to deploy this solution as code following this article. see attached json for template deployment. i am successfully deploying using frontend so subscriptions is not issue as showing in below error
[main.json](https://github.com/user-attachments/files/16682087/main.json)

https://learn.microsoft.com/en-us/marketplace/programmatic-deploy-of-marketplace-products

but getting error

{"code": "MarketplacePurchaseEligibilityFailed", "message": "Marketplace purchase eligibilty check returned errors. See inner errors for details. "}

Inner Errors: 
{"code": "BadRequest", "message": "Offer with PublisherId: 'microsoftcorporation1620879115842', OfferId: 'startstopv2' cannot be purchased due to validation errors. For more information see details. Correlation Id: '26debf7a-6ff4-4d87-acee-067e2da5b6b8' The Offer: 'startstopv2' cannot be purchased by subscription: '<subid>' as it is not to be sold in market: 'US'. Please choose a subscription which is associated with a different market. Correlation Id '26debf7a-6ff4-4d87-acee-067e2da5b6b8'.[{\"The Offer: 'startstopv2' cannot be purchased by subscription: '<subid>' as it is not to be sold in market: 'US'. Please choose a subscription which is associated with a different market. Correlation Id '26debf7a-6ff4-4d87-acee-067e2da5b6b8'.\":\"StoreApi\"}]"}

Please advise what wrong with these 4 values or any other parameters. see attached screenshot
![Screenshot 2024-08-20 at 5 43 37 PM](https://github.com/user-attachments/assets/7c8c3bc3-cad5-4a35-bd62-966b995e9ab4)

            "plan": {
                "name": "startstopv2-08252021",
                "product": "startstopv2",
                "publisher": "microsoftcorporation1620879115842",
                "version": "StartStopV2-AZ"
            },

**Comment by jeffw16** [comment]
It looks like you are trying to deploy the version `StartStopV2-AZ`. Can you do just `StartStopV2`?

**Comment by goranvrbaski** [comment]
Having the same issue, tried with `StartStopV2-AZ ` and `StartStopV2`. Any solution to this issue?

**Comment by jeffw16** [comment]
@goranvrbaski If you tried to deploy within the past 16 hours, please try again now. There was an issue that has just been fixed. We apologize for the inconvenience.

**Comment by goranvrbaski** [comment]
@jeffw16 just tried once again, still the same issue.

**Comment by jeffw16** [comment]
If you are still receiving this issue, then it is different. We are not seeing this issue appear with the vast majority of our users. You can reach out to Azure Support for further assistance.
