### ISSUE TITLE
August 19 release broke Start/Stop VM TriggerAutoUpdate function

### ISSUE THREAD

**Issue by jgroves71** [microsoft/startstopv2-deployments#134]
It appears that my installation of Start/Stop VM v2 was attempted to be AutoUpgraded on August 19. The daily scheduled attempt to AutoUpdate appears to have failed and broken the function app completely - the logic apps now fail and are no longer able to invoke the function app at all.

The activity log for the function app shows that a website extension update failed. JSON of the error message is below.

"statusMessage": "{\"status\":\"failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'failed'.\",\"details\":[{\"code\":\"Failed\",\"message\":\"Package deployment failed\\r\\nARM-MSDeploy Deploy Failed: 'Microsoft.Web.Deployment.DeploymentDetailedUnauthorizedAccessException: Unable to perform the operation (\\\"Delete File\\\")  for the specified directory (\\\"C:\\\\home\\\\site\\\\wwwroot\\\\bin\\\\Microsoft.Azure.Functions.Extensions.dll\\\"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER. ---&gt; Microsoft.Web.Deployment.DeploymentException: The error code was 0x80070005. ---&gt; System.UnauthorizedAccessException: Access to the path 'C:\\\\home\\\\site\\\\wwwroot\\\\bin\\\\Microsoft.Azure.Functions.Extensions.dll' is denied.\\r\\n   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)\\r\\n   at Microsoft.Web.Deployment.FileEx.Delete(String path)\\r\\n   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)\\r\\n   --- End of inner exception stack trace ---\\r\\n   --- End of inner exception stack trace ---\\r\\n   at Microsoft.Web.Deployment.FilePathProviderBase.HandleKnownRetryableExceptions(DeploymentBaseContext baseContext, Int32[] errorsToIgnore, Exception e, String path, String operation)\\r\\n   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.DeleteOperation(DeploymentSyncContext syncContext)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.Delete(DeploymentSyncContext syncContext)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleDelete(DeploymentObject destObject, DeploymentObject sourceParentObject)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete) in C:\\\\__w\\\\1\\\\s\\\\src\\\\hosting\\\\wdeploy\\\\Microsoft.Web.Deployment.WebApi\\\\AppGalleryPackage.cs:line 343\\r\\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__25.MoveNext() in C:\\\\__w\\\\1\\\\s\\\\src\\\\hosting\\\\wdeploy\\\\Microsoft.Web.Deployment.WebApi\\\\Controllers\\\\DeploymentController.cs:line 495'\"}]}}",

**Comment by jeffw16** [comment]
Hello, we are sorry to hear you are experiencing issues with your StartStop V2 instance after the auto upgrade process was unable to resolve a lockfile permissions issue inherent in Azure Functions and one that we have no control over. Please refer to the following message for more information: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492

**Comment by jgroves71** [comment]
Thank you Jeff, yes, redeploying from the marketplace did resolve the issue.
