### ISSUE TITLE
503 Error for StartVM function

### ISSUE THREAD

**Issue by ElenaTyp** [microsoft/startstopv2-deployments#136]
We are receiving this error since Monday (August 26) on a daily basis for the scheduled VM start.
TriggerAutoUpdate is enabled and runs correctly, no changes have been performed on our end, is there anything else we should look at?

Thanks in advance

**Comment by leohoknows** [comment]
Very interesting... we are receiving the exact same error since August 19

**Comment by ElenaTyp** [comment]
I saw your issue, but thought it was fixed after TriggerAutoUpdate run?
(it runs every few days in our case and hasn't fixed it...)

**Comment by ElenaTyp** [comment]
Opened a ticket with MS myself this morning, still pending an update there though (will need to follow up and try to get some more traction tomorrow otherwise)

**Comment by jeffw16** [comment]
Hello, we are sorry to hear you are experiencing issues with your StartStop V2 instance after the auto upgrade process was unable to resolve a lockfile permissions issue inherent in Azure Functions and one that we have no control over. Please refer to the following message for more information: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492
