### ISSUE TITLE
Deployment to blob storage using WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by jgroves71** [microsoft/startstopv2-deployments#137]
Hello,

We would like to be able to turn off the SAS Keys for the storage account created by this solution and use only RBAC-based identity, which means avoiding use of Azure Files which currently does not support identity-based access.

Is the StartStopV2.zip file from this archive suitable for use by uploading it as is to Blob storage and setting the WEBSITE_RUN_FROM_PACKAGE environment variable to the URL of the Blob after granting Blob contributor access to the function account managed identity? Does this solution support running in this mode? So far I have not been able to get it to work.

**Comment by jeffw16** [comment]
If you install from the marketplace, the latest version should have support for managed identity-based auth to the storage account.

This comment may be of interest: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492
