### ISSUE TITLE
FUNCTIONS_WORKER_RUNTIME mode

### ISSUE THREAD

**Issue by ScottMonolith** [microsoft/startstopv2-deployments#138]
Hello,

I received this warning that says it will turn into an error:

`The 'FUNCTIONS_WORKER_RUNTIME' is set to 'dotnet-isolated', which does not match the worker runtime metadata found in the deployed function app artifacts. The deployed artifacts are for 'dotnet'. See https://aka.ms/functions-invalid-worker-runtime for more information. The application will continue to run, but may throw an exception in the future.`

I have tried to redeploy again as there is some conflicting update related information (GitHub indicates you can just use the TriggerAutoUpdate function, while the learn.microsoft.com docs state that function is deprecated and you should just 'install the latest from GitHub' in order to update).

Please advise.

**Comment by jeffw16** [comment]
Sorry for the confusion @ScottMonolith. Please refer to this comment for our official advised course of action as of May 2024: https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492

**Comment by ScottMonolith** [comment]
Hm, I already did that - I will try again, thanks for the quick response.
