### ISSUE TITLE
Deployment Validation Failed: Circular Dependency. Code: InvalidTemplate

### ISSUE THREAD

**Issue by sccjas** [microsoft/startstopv2-deployments#14]
Hi, I ran the deployment for GCC subscription. Got the following error during validation:

Deployment template validation failed: 'Circular dependency detected on resource: '/subscriptions/[subID]/resourceGroups/[RG]/providers/Microsoft.Web/sites/func-SHR-startstopv2eydsvskgkffla'. Please see https://aka.ms/arm-template/#resources for usage details.'. (Code: InvalidTemplate)

Tried different field variables still no luck.

**Comment by balas77** [comment]
@sccjas - Sorry to hear that. Have you tried to redeploy that? Can you share the screenshot of that error? I did tried to deploy twice and unable to catch that issue.

**Comment by sccjas** [comment]
I have the same problem with other GCC subscriptions but not Commercial subscriptions.   The deployment template appears to be the same as far as 'dependency on' sections.

![vmstartstop](https://user-images.githubusercontent.com/48775147/127217498-76968d21-5fb9-4322-b579-7da84fee2398.png)

**Comment by balas77** [comment]
ok got it. Found the issue in Fairfax template. Working on it now and will keep you posted once ready.

**Comment by balas77** [comment]
I have fixed it now. Can you please try it and let me know the outcome?

**Comment by sccjas** [comment]
Works! Thanks.

**Comment by balas77** [comment]
Thanks a lot!
