### ISSUE TITLE
Running SSV2_AutomationUpdateGA failed in error

### ISSUE THREAD

**Issue by desmphil** [microsoft/startstopv2-deployments#144]
Im Global Admin and Subscription Owner, 
First Function App was created a while ago but it didnt seem to update automatically to the latest isolated version.
So i ran the Get Latest Version (Existing Users)

Non-availability zone-based solution
If you originally deployed the solution using the default Plan selection, a Function App Consumption plan and a locally redundant Storage account are deployed. In this case, use this template.

Deploy to Azure

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"Failed\",\r\n        \"message\": \"Package deployment failed\\r\\nARM-MSDeploy Deploy Failed: 'Microsoft.Web.Deployment.DeploymentDetailedUnauthorizedAccessException: Unable to perform the operation (\\\"Delete File\\\")  for the specified directory (\\\"C:\\\\home\\\\site\\\\wwwroot\\\\bin\\\\Azure.Core.dll\\\"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER. ---&gt; Microsoft.Web.Deployment.DeploymentException: The error code was 0x80070005. ---&gt; System.UnauthorizedAccessException: Access to the path 'C:\\\\home\\\\site\\\\wwwroot\\\\bin\\\\Azure.Core.dll' is denied.\\r\\n   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)\\r\\n   at Microsoft.Web.Deployment.FileEx.Delete(String path)\\r\\n   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)\\r\\n   --- End of inner exception stack trace ---\\r\\n   --- End of inner exception stack trace ---\\r\\n   at Microsoft.Web.Deployment.FilePathProviderBase.HandleKnownRetryableExceptions(DeploymentBaseContext baseContext, Int32[] errorsToIgnore, Exception e, String path, String operation)\\r\\n   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.DeleteOperation(DeploymentSyncContext syncContext)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.Delete(DeploymentSyncContext syncContext)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleDelete(DeploymentObject destObject, DeploymentObject sourceParentObject)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)\\r\\n   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)\\r\\n   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete) in C:\\\\__w\\\\1\\\\s\\\\src\\\\hosting\\\\wdeploy\\\\Microsoft.Web.Deployment.WebApi\\\\AppGalleryPackage.cs:line 343\\r\\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__25.MoveNext() in C:\\\\__w\\\\1\\\\s\\\\src\\\\hosting\\\\wdeploy\\\\Microsoft.Web.Deployment.WebApi\\\\Controllers\\\\DeploymentController.cs:line 495'\"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

![Image](https://github.com/user-attachments/assets/16ede428-cf61-49c7-a4b1-c46421b0747e)

**Comment by jeffw16** [comment]
Please see https://github.com/microsoft/startstopv2-deployments/issues/116#issuecomment-2104845492

**Comment by desmphil** [comment]
Hi, could you update the **known issue** in the wiki page, this would be more helpfull than searching around.

Thank you

**Comment by desmphil** [comment]
The solution provided to, re-deploy doesnt even work... it will just crash too, because some objects already exists.
Also all the Logic Apps stops working, un-authorized.
The Dashboard also breaks down.

You should recommend just to start over because your solutions BREAKS everything, more than it can fix.

![Image](https://github.com/user-attachments/assets/966b0c1f-9c9d-4b84-abf0-bf951c82159f)


{
  "code": "DeploymentFailed",
  "target": "/subscriptions/b7e8b19a-065f-4624-8ed2-c592b6df71e8/resourceGroups/Prod-Automation-StartStop/providers/Microsoft.Resources/deployments/StartStopV2_CreateAlerts",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "Scope can not be updated Activity ID: adc0d5bd-7092-4500-a2fa-05475b192ff1."
    },
    {
      "code": "BadRequest",
      "message": "Scope can not be updated Activity ID: b9668589-c7e9-41a9-8b79-446d51a15302."
    },
    {
      "code": "BadRequest",
      "message": "Scope can not be updated Activity ID: 3456fa68-ff4b-4c1a-bc03-e623b7cab8e3."
    }
  ]
}
