### ISSUE TITLE
Can you run multiple action groups with this solution?

### ISSUE THREAD

**Issue by arijnbeek** [microsoft/startstopv2-deployments#15]
It is possible to run multiple schedules, but is it also possible to create an action group for a specific schedule?
So for 1 set of VM's only the corresponding action group is triggered?

**Comment by balas77** [comment]
@arijnbeek - Currently 1 logic app is associated for 1 schedule and with 1 payload structure. If you need multiple then you can clone the logic app (probably rename it for better and easy identification) and configure the schedule with the different VM's.

**Comment by balas77** [comment]
Any further updates on this?

**Comment by arijnbeek** [comment]
I managed to create 2 more action rules with custom query's and each there own action group and scheduled logic app.

**Comment by balas77** [comment]
Great. Glad that it worked for you!
