### ISSUE TITLE
Logic app succeeds, but the VM doesn't shutdown

### ISSUE THREAD

**Issue by Technokf21** [microsoft/startstopv2-deployments#16]
I have followed the directions to configure a single vm to shutdown. It's a scheduled shutdown. I have tested it by running the trigger manually as well as setting the time. All instances run successfully, however, the VM never shuts down. I was previously using the V1 version and did not have any issues with the process. The solution is installed under a different subscription, however I updated the target subscription with the 'contributer' permissions.
I have included a couple of screenshots including the inputs for the scheduled logic app.
![image](https://user-images.githubusercontent.com/88043921/127172972-e08a6232-e08f-43d4-9e83-11caecc4cbae.png)

**Comment by svarga-msft** [comment]
Thanks for reaching out. Can you show what the output of those runs were? In the success output there should be a list of VMs which were targeted for action, that would be the first place to look as we debug this.

**Comment by Technokf21** [comment]
Sure: 
Is this what you are looking for:
![image](https://user-images.githubusercontent.com/88043921/127198874-e710dfe9-ec29-4264-bd4d-b781bd819964.png)

**Comment by Technokf21** [comment]
here's the request body info as well. 
![image](https://user-images.githubusercontent.com/88043921/127199285-d1e9bf4c-b4c7-4ab7-8b5a-1472f234cc84.png)

**Comment by svarga-msft** [comment]
Hi, first image isn't exactly what I'm looking for. Looking for the output that is shown when you open one of the previous runs of the runbook, like this:
![image](https://user-images.githubusercontent.com/68304251/127205418-1791c5e1-cbee-4195-b92e-376cfb3b5434.png)

However! I do see the issue in your payload, so the above screenshot is probably not needed. In your payload you're using the ResourceGroups array for operating on a single VM. In the ResourceGroups section of the payload you can specify resource group scopes, but not individual VMs. You'll want to add another property and array at the same level as ResourceGroups with the name "VMLists", or the easier solution would be to just rename "ResourceGroups" to "VMLists" in your payload. It should look like this:
![image](https://user-images.githubusercontent.com/68304251/127205879-76ee738f-f1b5-4050-abf8-ad4a345fc6a7.png)

**Comment by Technokf21** [comment]
Thank you! That was it! Appreciate your quick assistance!

**Comment by balas77** [comment]
@Technokf21 - I will close the issue now. If you need further assistance please do reach us.
