### ISSUE TITLE
Add Tag parameter please

### ISSUE THREAD

**Issue by teds21** [microsoft/startstopv2-deployments#17]
Most organizations require Tagging resources at the policy level.  Can someone please add that option in during deployment?  Current workaround is to manually exempt the resource group, then tag the resources and re-add it.

**Comment by balas77** [comment]
@teds21 - Thanks for reaching us. Could you help me to provide additional information regarding tag parameter? Are you looking for one generic tag parameter and add the tag value to all the resources including RG?

**Comment by teds21** [comment]
@balas77 - That's correct. One generic tag parameter defined as an object that can be utilized for all the tags/values the organization requires.  That would be applied to the resource group and all child resources underneath it.

**Comment by parojasmsft** [comment]
@teds21 Hi can you reach out to us via this email address: startstopv2team@microsoft.com 
I would like to have a more in depth conversation with you about the tags feature you are requesting. Also are you internal to microsoft or an external customer?

**Comment by jonathan-bier-by** [comment]
@ted21 - Total agree on the tagging issue.  We hit exactly the same issue deploying.

**Comment by jonathan-bier-by** [comment]
@parojasmsft - When we create a resource group, our policies require 5 tags be attached.  Your deployment scripts don't work because those tags aren't on the resource group that the deployment scripts create.  To deploy, I had to have someone suspend the policy, deploy the app, and then remediate the resource group and apply the missing tags to the resources deployed.

**Comment by balas77** [comment]
We're planning to add a default tags (SolutionName : StartStopV2) to RG and all the underlying resources.

**Comment by balas77** [comment]
It is now added in deployment package.
