### ISSUE TITLE
Reserve ip address option

### ISSUE THREAD

**Issue by alxnik** [microsoft/startstopv2-deployments#19]
When manually stopping a VM via the azure portal, the is an option to reserve the ip address. Does this option exist in the automation? It is an essential option in certain use cases.

**Comment by svarga-msft** [comment]
Hi, right now we don't have this available as a configurable setting. We will take this as a feature request and put it in our backlog.

Thanks

**Comment by balas77** [comment]
Closing this issue as we moved this as feature request in our backlog.
