### ISSUE TITLE
Documentation doesn't enable logic apps

### ISSUE THREAD

**Issue by DennisGaida** [microsoft/startstopv2-deployments#20]
Should documentation issues be left here or in the official azure repo?

The documentation here is missing a simple step to get going with the template
https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/deploy

You actually have to enable one of the logic apps (or more than one) to make the solution work - so all of the scenarios are missing a step 6: "Enable the logic app via the overview panel".

**Comment by balas77** [comment]
@DennisGaida - Yes any issues related to Start/Stop V2 can be raised here. Sure I will add that step in the doc. Thanks for catching that 👍

**Comment by balas77** [comment]
Changes done and closing this issue!
