### ISSUE TITLE
Error while running stop or start logic app

### ISSUE THREAD

**Issue by mmilhomem** [microsoft/startstopv2-deployments#21]
I am getting the following error while running the start or stop logic app. I already checked and both the fuction and logic app have contributor at the subscription level

{
    "runStatus": "Failed",
    "runError": {
        "code": "500",
        "message": "{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"The client '7e57365d-2eec-476b-8d15-72291373ff8d' with object id '7e57365d-2eec-476b-8d15-72291373ff8d' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resources/read' over scope '/subscriptions/f3533fa8-fb94-4f09-98c6-e33601edeb74' or the scope is invalid. If access was recently granted, please refresh your credentials.\",\"ExceptionType\":\"Microsoft.Rest.Azure.CloudException\",\"StackTrace\":\"   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.ListWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)\\r\\n   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.ListAsync(IResourcesOperations operations, ODataQuery`1 odataQuery, CancellationToken cancellationToken)\\r\\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionArmVirtualMachinesAsync(String subscriptionId) in D:\\\\a\\\\1\\\\s\\\\StartStopAzureFunctions\\\\Clients\\\\AzureVirtualMachineClient.cs:line 109\\r\\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionVirtualMachinesAsync(String subscriptionId, Boolean classicEnabled) in D:\\\\a\\\\1\\\\s\\\\StartStopAzureFunctions\\\\Clients\\\\AzureVirtualMachineClient.cs:line 98\\r\\n   at StartStopAzureFunctions.BusinessLogic.UserRequestTranslatorBL.GetAccessibleVmsForSubscriptionScopesAsync(IEnumerable`1 subscriptionIds, Boolean classicEnabled) in D:\\\\a\\\\1\\\\s\\\\StartStopAzureFunctions\\\\BusinessLogic\\\\UserRequestTranslatorBL.cs:line 70\\r\\n   at StartStopAzureFunctions.Workflows.VirtualMachineScheduledRequestWorkflow.StartWorkflowAsync(ScheduledRequest scheduledRequest) in D:\\\\a\\\\1\\\\s\\\\StartStopAzureFunctions\\\\Workflows\\\\VirtualMachineScheduledRequestWorkflow.cs:line 83\\r\\n   at StartStopAzureFunctions.ScheduledRequestFunction.RunAsync(ScheduledRequest scheduledRequest) in D:\\\\a\\\\1\\\\s\\\\StartStopAzureFunctions\\\\ScheduledRequestFunction.cs:line 32\"}"
    }
}

**Comment by balas77** [comment]
Do you see any errors in the deployment? Making sure the deployment is clean. 
Can you share your payload to our email startstopv2team@microsoft.com?

**Comment by balas77** [comment]
@mmilhomem - Do you have any updates?

**Comment by balas77** [comment]
Since no response I am closing this but feel free to reopen when you reach us with the payload.
