### ISSUE TITLE
Ability to perform the start/stop schedule based on VM tags?

### ISSUE THREAD

**Issue by scottthistle** [microsoft/startstopv2-deployments#22]
This is more of a feature request. We would like the ability to apply tags to the VM (i.e. vmruntime=08:00-17:00) and have the automation start/stop VMs based on that tag value.

**Comment by balas77** [comment]
@scottthistle - Thanks for sharing this idea. You can achieve the same by scheduling our logic apps (start by 8a and stop by 5p). I will add this to our backlog and based on the interest from other customers we will consider this.

**Comment by scottthistle** [comment]
We would like to schedule based on a tag value. Is that possible?

i.e.

Server1 has tag value of 0900-1600
Server2 has tag value of 1000-2000


Scott Thistle, CRISC (he/him)
Technical Lead Cloud Ops/DevOps,FinancialOps
Cloud Business Office
Corporate Services
Office: 1.403.766.3737 | Cell: 1.403.404.0423
***@***.******@***.***>
Calgary, Alberta

**Comment by balas77** [comment]
Currently our solution doesn't support/perform the Start or Stop action based on the VM tags. We use VM tags only for Sequenced start and stop scenario which basically define the order of the VM execution. As mentioned before I will add this feature in our backlog and will address based on the priority. 

May I know how many VM's are you planning to configure based on the VM tags?

**Comment by scottthistle** [comment]
We currently have 100+ VMs and want to leverage this for about 60-70% of them. We have merged with a peer company and will be using it for about 300-400 of them as well. We currently use an in-house developed power shell automation but it currently requires a runas account per subscription. We would like to centralize on a supported solution. I was asked to submit the request by our Microsoft TAM/SE.

Scott Thistle
________________________________
