### ISSUE TITLE
Scheduled jobs / runbook are not running

### ISSUE THREAD

**Issue by Rafimd786** [microsoft/startstopv2-deployments#23]
I am using Start/ Stop VM version 2, I am creating this case based on following link 
https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/overview

Question: Are you using the Start Stop Solution, or a custom script?
Answer: I am using the Start-Stop VM Solution

Question: When did the problem begin?
Answer: Thu, Sep 2, 2021, 12:00 AM EDT

Question: Details
Answer: Starting from 2nd September Scheduled job / runbook is not working to start the VM, we are performing manual start. You can find last sucessfull job details below.

ScheduledStartStop_Child
9/2/2021, 9:30:54 PM
Completed
Azure
9/2/2021, 9:33:03 PM
ScheduledStartStop_Parent

**Comment by balas77** [comment]
@Rafimd786 - Is this problem related to V1 or V2? If it is V1 then please raise azure support ticket in the portal. If it is related to V2 then please do share the error details? 

V1 - Based on Azure Automation Account/Runbooks
V2 - Based on Azure Function Apps

**Comment by Rafimd786** [comment]
++ Johar from Azure support

Hi Team,

Given problem is for V2. I have already created Azure support ticket and they only suggested me to create ticket with GitHub support team.

Regarding the issue, there was no specific error which I am aware about but Azure VM start or stop Scheduled job / runbook was working fine till 2nd September. Suddenly it stopped working. Need your help to restart the job / runbook.

***@***.***

Thanks,
Rafi

**Comment by hki-237** [comment]
Here is the documentation for Start Stop V1: https://docs.microsoft.com/en-us/azure/automation/automation-solution-vm-management

**Comment by balas77** [comment]
@Rafimd786 - Please let me know if you're still looking for help regarding our V2 solution.

**Comment by Rafimd786** [comment]
Hi Team,

We have resolved the issue, please go ahead and close the case.

Thanks,
Rafi

**Comment by balas77** [comment]
Closing this since it's working fine now.
