### ISSUE TITLE
Bad Request for Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by sarahm7** [microsoft/startstopv2-deployments#24]
Hi! Hope you can assist, I'm receiving Bad Request when trying to implement this on our virtual machine scale set

**INPUT**

    "function": {
        "name": "stagingStartStopVM-FAvglt7nztx34dk/Scheduled",
        "id": "/subscriptions/XXXXXXXXXXXXXXX/resourceGroups/XXXXX_STAGING/providers/Microsoft.Web/sites/stagingStartStopVM-FAvglt7nztx34dk/functions/Scheduled",
        "type": "Microsoft.Web/sites/functions"
    },
    "body": {
        "Action": "stop",
        "EnableClassic": false,
        "RequestScopes": {
            "ExcludedVMLists": [],
            "VMLists": [         "/subscriptions/XXXXXXXXXXXXXXX/resourceGroups/XXXXX_STAGING/providers/Microsoft.Compute/virtualMachineScaleSets/stgngnode/virtualMachines/0",             "/subscriptions/XXXXXXXXXXXXXXXresourceGroups/XXXXX_STAGING/providers/Microsoft.Compute/virtualMachineScaleSets/stgngnode/virtualMachines/1",    "/subscriptions/XXXXXXXXXXXXXXX/resourceGroups/XXXXX_STAGING/providers/Microsoft.Compute/virtualMachineScaleSets/stgngnode/virtualMachines/2"
            ]
        }
    }
}

**OUTPUT**
```
{
    "statusCode": 400,
    "headers": {
        "Request-Context": "appId=cid-v1:9512cdc1-d4d2-40bc-be4c-e2ac00c2a572",
        "X-Content-Type-Options": "nosniff",
        "Date": "Fri, 17 Sep 2021 09:39:08 GMT",
        "Content-Length": "428",
        "Content-Type": "application/json; charset=utf-8"
    },
    "body": {
        "successful": false,
        "message": "Encountered a request scope with an invalid value. The provided resource ARM URI /subscriptions/XXXXXXXXXXXXXXX/resourceGroups/XXXXX_STAGING/providers/Microsoft.Compute/virtualMachineScaleSets/stgngnode/virtualMachines/0 is invalid. Uri should contain a provider of type /providers/Microsoft.Compute/virtualMachines or /providers/Microsoft.ClassicCompute/virtualMachines."
    }
}
```

Is there anyway to make this work for VMSS? Thanks!

**Comment by balas77** [comment]
Thanks for checking on this. Currently our solution doesn't support VMSS. We are planning to work on this sooner. I will update the public doc when it is ready.

**Comment by hki-237** [comment]
We have to wait for the feature to get added. As of now, this is not supported and there isn't another way to achieve this.

**Comment by balas77** [comment]
@sarahm7 - I will go ahead and close this now. When this feature is ready I will keep you posted!
