### ISSUE TITLE
Delete StartStopVMV2 dashboard by mistake - how can i get it back

### ISSUE THREAD

**Issue by dougkamp** [microsoft/startstopv2-deployments#25]
Hi,

Unfortunately we had problems with our dashboard and then it was deleted by mistake. Am I able to recreate it or upload it from somewhere?

Cheers,
Doug

**Comment by balas77** [comment]
We are thinking around options for customers to deploy the components separately in case if they want to redeploy only certain part of the solution. 

Currently it's not ready but I am happy to help you out offline if you can reach us via aoateamo@microsoft.com. I will share you the template and steps to deploy them.

**Comment by balas77** [comment]
Also I would like to understand the problem that you had with our dashboard.

**Comment by balas77** [comment]
@dougkamp - Any updates on this?

**Comment by dougkamp** [comment]
@balas77 I dont the the original problem but no data was appearing in the dashboard. I have created another instance of startstopv2 and have exported the dashboard and will modify it for the original instance where i deleted and then upload the dashboard again unless you can think of another quicker/better way?

**Comment by balas77** [comment]
I can share the dashboard template and you can directly deploy (from the azure portal template) the dashboard template in the same Start/Stop resource group. Your dashboard will be ready! I can certainly share the template & the steps once you reach me on the above mentioned email.

**Comment by dougkamp** [comment]
Thanks - I have sent you an email to you using startstopv2team@microsoft.com

**Comment by balas77** [comment]
I have responded back to you with the steps. Please do let me know the outcome!
