### ISSUE TITLE
Documentation about the content of sequencestart and sequencestop tags

### ISSUE THREAD

**Issue by AlexanderRijnbeek** [microsoft/startstopv2-deployments#27]
Anyone can tell me what i should put in the tags sequencestart and sequencestop? I can not find the relevent pointer of information about it in this solution.
Thanks in advanced

**Comment by bearmerino** [comment]
I have been searching for the same information. I would like to setup the proper order in which VMs shutdown and start-up but can't find any information. right not I'm having to create multiple schedules to make this work as I want. However, it seems the logic is there but can't figure out how to may the sequence work.

**Comment by ericqms** [comment]
Hi. Apologies for the lack of clarity in using this feature. We have taken a work item to improve the documentation for this feature and will be updating shortly & will reply back to this thread when it is ready.

**Comment by ericqms** [comment]
Hi again. Here's a pre-read of the instructions that will be going into the documentation. Let me know if it is clear & unblocks you.

The proper way to use the sequence functionality is to create a tag named sequencestart on each VM you wish to be started in a sequence. The tag value needs to be an integer ranging from 1 to N for each VM in the respective scope. The tag is optional and if not present, the VM simply won’t participate in the sequencing.

The same criteria applies to stopping VMs with only the tag name being different. Use sequencestop in this case.

Both tags can be used on the same VM without issue.

Hope this helps.

**Comment by bearmerino** [comment]
Ditto on the delay option. However, assuming that is not already there would the way we create that is by copying the logic app and just have a different start time? There is only 1 or two VMs I want started fully before the rest of the environment (I.e. DCs) but from there the rest just needed to start up in order. 

If we do have two or more logic app copies. Can you use the same numbers as values (should you?)? I.e. Sequence start is for rg1 that has the first group of VMs you want powered on and those VMs have the tags for start using 1-3. Then logic app copy has all other VMs in the subscription excluding the VMs from rg1 would I use the values of 1-15 or would/should start with values 4-18?

Thanks in advance,

**Comment by ericqms** [comment]
> So simple can it be. That's making a lot of sense. The question that remains is now is there a delay in between starting and stopping the vm's? If not can I put in a feature request for that :)

Hi @arijnbeek.

There currently is no delay other than the small amount of time it takes to verify that the intended action has been completed before moving onto the next. LOL, I have alerted our PM to capture this feature request. Are you thinking of VM specific delays or a global delay feature?

Look forward to your feedback.

**Comment by ericqms** [comment]
> Ditto on the delay option. However, assuming that is not already there would the way we create that is by copying the logic app and just have a different start time? There is only 1 or two VMs I want started fully before the rest of the environment (I.e. DCs) but from there the rest just needed to start up in order.
> 
> If we do have two or more logic app copies. Can you use the same numbers as values (should you?)? I.e. Sequence start is for rg1 that has the first group of VMs you want powered on and those VMs have the tags for start using 1-3. Then logic app copy has all other VMs in the subscription excluding the VMs from rg1 would I use the values of 1-15 or would/should start with values 4-18?
> 
> Thanks in advance,

Hi @bearmerino 

Yes, making a copy of the logic app would get your desired result.

In your scenario, I believe either numbering scheme would work since the RG scoped logic app won't have visibility to the VMs outside of it & the subscription scoped logic app will have the RG scoped VMs excluded. If it were me, however, I would probably start my second batch at 4 so if I were looking at VMs all up, it would make more logical sense what your intention is.
