### ISSUE TITLE
Roadmap for Start/Stop v2? Is there a committed schedule for Start/Stop v2 GA?

### ISSUE THREAD

**Issue by sdolgin** [microsoft/startstopv2-deployments#29]
Thanks for putting together this solution. Is there a publicly announced date for Microsoft to make Start/Stop v2 generally available? Given the statement that the v1 solution support ends in 2022 I would like to know our options for long term support for this type of automated solution. Additionally, are there any plans to open source the underlying functions app? 

Thanks again!

**Comment by ktuuliainen** [comment]
How about the GA date? If I read the date correctly in the comment above 1st November 2021, but still all docs state preview?

**Comment by ajpogue** [comment]
Is there a GA date at this time?

**Comment by georgeOsdDev** [comment]
@balas77 
I think v2 is already GA, but there are `preview` keyword in marketplace
https://github.com/microsoft/startstopv2-deployments/issues/88
