### ISSUE TITLE
Support pre-stop/post-start scrtips for VM start/stop feature

### ISSUE THREAD

**Issue by TheMorganator** [microsoft/startstopv2-deployments#31]
It would be useful to be able to define per-VM actions to be executed inside the VM before stopping and after starting. Many applications have stop procedures that exceed the Azure limit allowed for shutdowns.

**Comment by awaadhwa** [comment]
Hi Morgan. What actions/scripts were you thinking of implementing? I can take this in as a feature request and add it to the backlog.

**Comment by grimstoner** [comment]
Not sure if we can vote on requests, but this would be useful in our scenario as well. We have a custom in-memory database application that needs to flush to disk by stopping the Windows service before shutting down the machine.

**Comment by ericqms** [comment]
Hi @grimstoner.

While I don't think voting is supported here, your 'vote' has been counted with us. :-)
