### ISSUE TITLE
Classic App Insights

### ISSUE THREAD

**Issue by dcbrown16** [microsoft/startstopv2-deployments#33]
Hi, it looks like the current deployment creates classic Application Insights resources.
Are there any plans to support creating a workspace-based AI resource with the start/stop v2 feature in the future?
Please contact me internally at v-dibr if needed, this is related to a customer inquiry through Pro Direct support.

**Comment by dcbrown16** [comment]
Related to that, I assume it's fine to migrate the created AI to workspace-based if desired?

**Comment by balas77** [comment]
@dcbrown16 - Yes we do create the classic AI resource. We're currently working on to include the Log Analytics workspace based Application Insights sooner. Yes it's fine to migrate the existing classic --> workspace-based for Start/Stop V2 and it works fine. Before migrate you can create a new LA workspace and map that during the migration process.

**Comment by dcbrown16** [comment]
Great, thank you!
