### ISSUE TITLE
Restart VM

### ISSUE THREAD

**Issue by schottky81** [microsoft/startstopv2-deployments#34]
Hi there,

Is there an action for "Restart" or do we need to schedule a stop and a start to reboot virtual machines?

**Comment by awaadhwa** [comment]
Hi Raphaël, we don't have this action currently. Could you possibly elaborate on your use case so that I can take this in as a feature request and add it to the backlog?

**Comment by balas77** [comment]
@schottky81 - Currently SSV2 doesnt have direct ReStart action and yes you can achieve with stop and start logic apps or with single logic app you can configure multiple schedule function app.

**Comment by schottky81** [comment]
Thank you for your reply.
I checked with my client and the use case is the following:
The reboot function with logic app could be interesting because we have a few AVD VMs used by a lot of user dispatched around the world with different time zones. As AVD VMs are running Windows 10 OS it will be interesting to have the possibility to restart the computer on a schedule.

**Comment by balas77** [comment]
@schottky81 - This is pretty new use case and I will add this to our backlog on the reboot functionality. 

As mentioned above you can use stop and stop together. Currently logic app **recurrence** task should allow you to select the time zone and you can configure the VMs that belongs to that time zone via the payload. You can use multiple logic apps (you can clone) per schedule for each specific time zone.  

![image](https://user-images.githubusercontent.com/64924532/142151201-8bc52e08-4d95-461a-a067-e7cdee941d98.png)

**Comment by schottky81** [comment]
@balas77 - Thanks for your support on this. It is really appreciated.
