### ISSUE TITLE
Select in-scope VM's by Tag

### ISSUE THREAD

**Issue by shanecastle-osharp** [microsoft/startstopv2-deployments#36]
It would be very useful to be able to filter a subset of VM's to start/stop via a tag.

Is this feature on the backlog?

**Comment by awaadhwa** [comment]
Hi Shane. Yes, this feature is on the backlog.

**Comment by shanecastle-osharp** [comment]
Sounds great.

The common use case I run across is:

1. Selectively shutting down VMs tagged with something like "AutoShutdown": "true"
2. Having a tag or set of tags for shutdown time w/timezone 
3. A mechanism for creating exceptions to the automated shutdown.

That's all I have for now, thanks.

**Comment by cpiment** [comment]
Hi @awaadhwa , are there any news regarding this feature? We have reviewed the documentation and it seems that machines can be only targeted by subscription, resource group, or by listing each and every machine.
