### ISSUE TITLE
Naming convention of created resources

### ISSUE THREAD

**Issue by grimstoner** [microsoft/startstopv2-deployments#39]
Hi

I understand why it is a "nice" feature to append random characters at the end of the specified Function App and Storage Account names to ensure they are globally unique.

However, in our environment we have strict naming conventions, and the random characters break the convention. I'd much rather have the deployment fail due to a non-globally unique name, than have the generated resources break my naming convention. 

As another naming-related feature request, could you make setting the name of the generated Dashboard user-definable during deployment as well?

**Comment by balas77** [comment]
@grimstoner - Thanks for reaching us. Currently we will _not_ be able to avoid appending the unique string on the resource name until we develop our marketplace item as native gallery to support the resource creation functionality directly from the blade. I will add this request in our backlog and see if this is a common request from other customers. Same applicable for user-definable dashboard name request.

**Comment by balas77** [comment]
@grimstoner - Unfortunately we are not able to remove this functionality now hence currently closing this issue.
