### ISSUE TITLE
Savings & Cost Functions

### ISSUE THREAD

**Issue by ktuuliainen** [microsoft/startstopv2-deployments#40]
The documentation mentions the below functions that calculates cost and savings. Where can I find more about these? Such as the result of them, how much has been saved by using the solution? 

CostAnalyticsFunction: This function calculates the cost to run the Start/Stop V2 solution on a monthly basis.
SavingsAnalyticsFunction: This function calculates the total savings achieved by the Start/Stop V2 solution on a monthly basis.
VirtualMachineSavingsFunction: This function performs the actual savings calculation on a VM achieved by the Start/Stop V2 solution.

**Comment by svarga-msft** [comment]
You can look in your app insights, specifically the customMetrics.

These two queries will return metrics about cost, and savings
**customMetrics | where name == "NoPiiDeploymentCostDaily"**
**customMetrics | where name == "NoPiiVirtualMachineResponsibleSavings"**

They both have different scopes, but if you query each of those, and explore the properties of the custom dimensions within those events, you can write queries to analyze the cost and savings.

If you have questions about these events feel free to ask.

**Comment by ktuuliainen** [comment]
No results if I run the provided queries. 

customMetrics | distinct name

Gives the list below, no events with the name "NoPiiDeploymentCostDaily" nor  "NoPiiVirtualMachineResponsibleSavings"  

name
HeartbeatState
AutoStopVM Count
AutoStopVM AvgDurationMs
AutoStopVM MaxDurationMs
AutoStopVM MinDurationMs
AutoStopVM Successes
AutoStopVM Failures
AutoStopVM SuccessRate
HeartBeatAvailabilityTest Count
HeartBeatAvailabilityTest AvgDurationMs
HeartBeatAvailabilityTest MaxDurationMs
HeartBeatAvailabilityTest MinDurationMs
HeartBeatAvailabilityTest Successes
HeartBeatAvailabilityTest Failures
HeartBeatAvailabilityTest SuccessRate
AutoStop Count
AutoStop AvgDurationMs
AutoStop MaxDurationMs
AutoStop MinDurationMs
AutoStop Successes
AutoStop Failures
AutoStop SuccessRate
Scheduled Count
Scheduled AvgDurationMs
Scheduled MaxDurationMs
Scheduled MinDurationMs
Scheduled Successes
Scheduled Failures
Scheduled SuccessRate
VirtualMachineRequestOrchestrator Count
VirtualMachineRequestOrchestrator AvgDurationMs
VirtualMachineRequestOrchestrator MaxDurationMs
VirtualMachineRequestOrchestrator MinDurationMs
VirtualMachineRequestOrchestrator Successes
VirtualMachineRequestOrchestrator Failures
VirtualMachineRequestOrchestrator SuccessRate
VirtualMachineRequestExecutor Count
VirtualMachineRequestExecutor AvgDurationMs
VirtualMachineRequestExecutor MaxDurationMs
VirtualMachineRequestExecutor MinDurationMs
VirtualMachineRequestExecutor Successes
VirtualMachineRequestExecutor Failures
VirtualMachineRequestExecutor SuccessRate
CostAnalyticsFunction Count
CostAnalyticsFunction AvgDurationMs
CostAnalyticsFunction MaxDurationMs
CostAnalyticsFunction MinDurationMs
CostAnalyticsFunction Successes
CostAnalyticsFunction Failures
CostAnalyticsFunction SuccessRate
SavingsAnalyticsFunction Count
SavingsAnalyticsFunction AvgDurationMs
SavingsAnalyticsFunction MaxDurationMs
SavingsAnalyticsFunction MinDurationMs
SavingsAnalyticsFunction Successes
SavingsAnalyticsFunction Failures
SavingsAnalyticsFunction SuccessRate
VirtualMachineSavingsFunction Count
VirtualMachineSavingsFunction AvgDurationMs
VirtualMachineSavingsFunction MaxDurationMs
VirtualMachineSavingsFunction MinDurationMs
VirtualMachineSavingsFunction Successes
VirtualMachineSavingsFunction Failures
VirtualMachineSavingsFunction SuccessRate

**Comment by svarga-msft** [comment]
Over what time period did you look when querying those? The savings function only runs a few times a month, and the cost only once a day.

It's possible you might have an older installation as well, these features were only released in the past few months. When did you install?

**Comment by ktuuliainen** [comment]
Deployment done early November, looked at data from beginning of November till now. 

I can see that the SavingsAnalyticsFunction has executed 2021-11-15 by running the below query:
traces | where operation_Name contains "SavingsAnalyticsFunction"

And the traces will show messages like the below, to me it looks like it has calculated some saving for the VMs, but without any documentation its just my guesses. 

Adding 115.70532710602777 of /subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/rg-test/providers/Microsoft.Compute/virtualMachines/testvm

**Comment by svarga-msft** [comment]
You're right, we use some fuzzy logic to come up with a best guess around the impact and savings start stop has had for each VM.

If you'd like. I could check our logs for your deployment. Shoot me an email at svarga@microsoft.com

**Comment by ktuuliainen** [comment]
When "SavingsAnalyticsFunction" triggers it executes and I did observe that it puts items on the storage queue "savings-request-queue". The items contain the resource id for the VM, time period (2021-11-01 to 2021-12-01) and a value for "ResponsibleDownTime" (I assume this represents the amount of hours the solution thinks it is responsible for having the VM deallocated)

Once the items appear on the queue the other function "VirtualMachineSavingsFunction" picks them up and I can also observer in the Application Insights log that it detects the new items. And in Application Insights I can see some logs in "traces" that the REST API for cost management is called (https://management.azure.com/{0}/providers/Microsoft.CostManagement/query?api-version=2019-11-01). And it looks to receive some response. 

Further If I run the below query 
traces | where message == "n/a" and operation_Name == "VirtualMachineSavingsFunction"

I can see in the results if I look at the "customDimensions" results like:
op__Name:  NoPiiVirtualMachineResponsibleSavings
prop__Value: 0.0074336954453469994

Indicating it has done some calculation or received some answer. But still nothing running the suggested queries:
customMetrics | where name == "NoPiiDeploymentCostDaily"
customMetrics | where name == "NoPiiVirtualMachineResponsibleSavings"

Looking into the "StartStopAzureFunctions.dll" used by the solution, observed that the REST API is queried https://management.azure.com/{0}/providers/Microsoft.CostManagement/query?api-version=2019-11-01

and if I interpret the code correctly (I'm no a programmer) there is "totalCostUSD" and "CostUSD" used for aggregation in the request. 

Do the currency make any difference (e.g. subscription state another currency than USD)? Or subscription type (such as EA, EA Dev/Test, VisualStudioEnterprise, etc)?

Anyhow in the end I think it would be nice to get some representation and visualization of cost (of the solution) as well as the savings made by using  the solution in the provided Dashboard

**Comment by danfaulkner81** [comment]
Being able to display the cost savings on the dashboard would be really useful.

I'm having the same experience, running the below displays no information. 
customMetrics | where name == "NoPiiDeploymentCostDaily"
customMetrics | where name == "NoPiiVirtualMachineResponsibleSavings"

If I run this query 
traces | where message == "n/a" and operation_Name == "VirtualMachineSavingsFunction"

I'm only able to see information from 48 hours or later time range, is that correct?

**Comment by awaadhwa** [comment]
Hi Dan, I can take this in as a feature request and add it to the backlog. I don't guarantee that it will be added, but we will review it further.

**Comment by ktuuliainen** [comment]
Hi, 

It would be really useful to get the insights of both what the solution costs (or at least some trend graph) as well as the savings achieved using the solution in an easy way in the Dashboard. 

One of the main purposes with a solution like this from my perspective would be to save costs by turning of VMs and thus actually seeing some numbers on the savings would be great. 

Some more documentation on what the solution logs in Application Insights would also be helpful, then at least we could have a better understanding of the available data and could more easily figure out our own queries as well.

Especially as it looks like the case that we are not getting out any data using the suggested queries (e.g. customMetrics | where name == "NoPiiDeploymentCostDaily" and customMetrics | where name == "NoPiiVirtualMachineResponsibleSavings")

Traces looks to be where to find information

traces | where customDimensions["prop__Name"] contains "NoPiiVirtualMachineResponsibleSavings"

traces | where customDimensions["prop__Name"] contains "NoPiiDeploymentCost"

Using below query looks to give a graph on the daily costs (if I understand the data provided by the solution correctly)

traces
| where customDimensions["prop__Name"] contains "NoPiiDeploymentCost"
| extend UsageDate = tostring(customDimensions.prop__UsageDate)
| extend UsageCost = todouble(customDimensions.prop__Value)
| project UsageDate, UsageCost
| sort by UsageDate asc 
| render timechart 

Further on the meaning of the different values logged by the solutions are what I believe the below, but since there is no documentation about them its hard to verify. 

traces
| where customDimensions["prop__Name"] contains "NoPiiVirtualMachineResponsibleSavings"

From the customDimensions I think the following are relevant:
prop__DeploymentResourceGroup: Resource group where the start/stop solution is deployed
prop__DeploymentSubscription: Subscription where the start/stop solution is deployed
prop__Name: NoPiiVirtualMachineResponsibleSavings
prop__SavingsQueryStartPeriod: Start date of the saving period (example value: 2021-11-01T00:00:00.0000000Z), I assume the saving period is one month
prop__TargetResourceCorrelationId: Identifier for the virtual machine 
prop__TargetResourceGroup: Resource group where the virtual machine is deployed
prop__TargetSubscription: Subscription where the virtual machine is stored
prop__Value: Estimated savings (example value: 6.535587155585392) that have been achieved using the solution for the particular VM and period. What currency is used is unclear to me.


traces
| where customDimensions["prop__Name"] contains "NoPiiVirtualMachineResponsibleSavings"

From the customDimensions I think the following are relevant:
prop__DeploymentResourceGroup: Resource group where the start/stop solution is deployed
prop__DeploymentSubscription: Subscription where the start/stop solution is deployed
prop__Name: NoPiiVirtualMachineResponsibleDownTime
prop__SavingsQueryStartPeriod: Start date of the saving period (example value: 2021-11-01T00:00:00.0000000Z), I assume the period is one month for the period
prop__TargetResourceCorrelationId: Identifier for the virtual machine 
prop__TargetResourceGroup: Resource group where the virtual machine is deployed
prop__TargetSubscription: Subscription where the virtual machine is stored
prop__Value: Estimated amount of hours (example value: 421.68250310347224) that the solution has stopped the particular VM during the period.

**Comment by awaadhwa** [comment]
Thank you for the additional information! I'll take a note of this.
