### ISSUE TITLE
Start/Stop VMs in Azure from Monday to Firday 

### ISSUE THREAD

**Issue by chandanat** [microsoft/startstopv2-deployments#41]
we have on RS having multiple VM, I just want to schedule auto Start and Stop particular VM from Monday to Firday.
Can someone help with this?

**Comment by svarga-msft** [comment]
Hi, want to understand your situation better. If I understand correctly, you want to schedule to turn all the VMs within a resource group on and off from Monday to Friday? For example, maybe turn all the VMs on at 9am and off at 5pm everyday m-f?

**Comment by balas77** [comment]
@chandanat - You can achieve this in few ways via ResourceGroups scope or VMLists scope that you define in the payload. Please do refer the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/deploy#scheduled-start-and-stop-scenario) on that. 
- If via RG scope, then you can use ExcludedVMLists to ignore from the action and target only the VMs that you need.
- If via VM scope, then it's pretty straight that you list the VMs in the payload.

If you want to target set of VMs on different time to start and stop, then you can clone the existing logic app (probably rename this based on the schedule) and have separate one for different timings.

Please do let me know if this helps!
