### ISSUE TITLE
Schedules not being triggered

### ISSUE THREAD

**Issue by tipiri2001** [microsoft/startstopv2-deployments#42]
Hi

I completed the configuration for start and stop under schedule, configured start time to avoid logic app to run after enabling it, nothing happened when schedule was reached, i had to manually trigger the logic app to make it worth, happened on stop and start logic apps.

Thanks

**Comment by ngankimkhong** [comment]
Hi @tipiri2001 , we are working with you offline through email. Please respond back to the email on the information we requested.

**Comment by raldaba** [comment]
Closing this one since we are working 1:1 with @tipiri2001 via email
