### ISSUE TITLE
Schedule Stop/Start for Tagged VMs

### ISSUE THREAD

**Issue by Carcamo-ben** [microsoft/startstopv2-deployments#43]
Hey team! This is a great improvement of the previous version and seems great, but there is a feature missing that I really miss. Can we do something either in the json or somewhere else, so we can shut down vms automatically in a subscription if they have x tag?

**Comment by ericqms** [comment]
Hi Carcamo-ben

Thanks for the kind words and input regarding tag features. We do have a number of user requests that revolve around the use of tags.

V1 out of the box did not have support for tags other than sequencing (which still exists in v2). Is the scenario you mention below implemented via a modification on the OOB code base? We would love more details on your use case & your customization if that's what you did.

Thanks,
Eric Q.

From: Carcamo-ben ***@***.***>
Sent: Wednesday, January 12, 2022 12:01 PM
To: microsoft/startstopv2-deployments ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/startstopv2-deployments] Schedule Stop/Start for Tagged VMs (Issue #43)


Hey team! This is a great improvement of the previous version and seems great, but there is a feature missing that I really miss. Can we do something either in the json or somewhere else, so we can shut down vms automatically in a subscription if they have x tag?

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fstartstopv2-deployments%2Fissues%2F43&data=04%7C01%7Cericq%40microsoft.com%7C3281d5ae94494a9045c008d9d60638f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637776144488810100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a7Ivg8cGh3G%2B6fo2qt0E4mcjFZ5IeaGnIIcYYLz0z6U%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAP2D2QCAU4X7DOORHPM5JLLUVXMW5ANCNFSM5LZ3VLKA&data=04%7C01%7Cericq%40microsoft.com%7C3281d5ae94494a9045c008d9d60638f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637776144488810100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fO0VyQtqF5no%2B5AnWbljmFfAjmuzPxahiIYHxmLG1Og%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cericq%40microsoft.com%7C3281d5ae94494a9045c008d9d60638f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637776144488810100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7j65v%2FrcBCnuUY93Ponzu6lnpUTUWer2MkyqCqLox70%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cericq%40microsoft.com%7C3281d5ae94494a9045c008d9d60638f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637776144488810100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sMCroit7tVLnLWEkzEcyhF0OqYXZW2jJf%2BxnUtLc1hk%3D&reserved=0>.

**Comment by raldaba** [comment]
@Carcamo-ben Hi there, just double-checking if you wanted to provide more details on your implementation case. Otherwise, rest assured the demand for the tags support has been captured in our backlog. Thanks for chiming in!

**Comment by timamay** [comment]
I would just like to echo the request for support of Tags in the solution. I am currently using a solution provided by Charles Nemnom. Just as Microsoft has done in V2, his solution rest on the use of a Function. IMO, his solution is very simple to implement, crosses as many subscriptions as you like, and there is very little code that just looks for the existence of two tags, which values represent the start time and stop time of a VM. Obviously, it would be better to have a solution that is released and supported by Microsoft. If you want to know more about his solution, here is a link to it. Thank you for keeping this in the backlog.

https://charbelnemnom.com/schedule-azure-vm-using-azure-function/

**Comment by raldaba** [comment]
Thanks @timamay ! Rest assured we have added this request to our backlog and that meetings are happening on this as we speak. We appreciate the comments you and the rest of the community have provided us. It helps us prioritize what our users really want. Thanks again!

**Comment by timamay** [comment]
> Thanks @timamay ! Rest assured we have added this request to our backlog and that meetings are happening on this as we speak. We appreciate the comments you and the rest of the community have provided us. It helps us prioritize what our users really want. Thanks again!

Thank you for continuing to looking into adding this support. I would be happy to assist in any beta testing you may offer down the road.
