### ISSUE TITLE
ExcludedVMLists property support for finding keywords in a VM name

### ISSUE THREAD

**Issue by rjhernandez** [microsoft/startstopv2-deployments#44]
## Problem
I am trying to exclude a set of machines from being `started` on a schedule that are part of the included `ResourceGroups` but the name contains a specific key word.  During my tests, the `ExcludedVMLists` expression is being ignored. Is the use of star (*) as part of the beginning of the expression not supported?

## Example configuration of `ststv2_vms_ScheduleStart_start`
```js
{
  "Action": "start",
  "EnableClassic": false,
  "RequestScopes": {
    "ResourceGroups": [
      "/subscriptions/11111111-0000-1111-2222-444444444444/resourceGroups/rg2/"
    ],
    "ExcludedVMLists": [
      "*doNotStart*"
    ]
  }
}
```

Ref: https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/deploy#scheduled-start-and-stop-scenario

**Comment by balas77** [comment]
@rjhernandez That's correct. As mentioned in the doc **'*'** wildcard will have to use as suffix. For example if you have VMs with AZdev1, AZdev2 then you can specify AZ*

**Comment by rjhernandez** [comment]
> @rjhernandez That's correct. As mentioned in the doc **'*'** wildcard will have to use as suffix. For example if you have VMs with AZdev1, AZdev2 then you can specify AZ*

Yikes, that does not work with my naming conventions.  Can you point me to the doc? URL?

**Comment by balas77** [comment]
Here is the doc https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/deploy
![image](https://user-images.githubusercontent.com/64924532/151436497-9a8389c2-708c-493a-b4ec-9f5b3c037569.png)

**Comment by raldaba** [comment]
@rjhernandez Closing this issue, but do reply back if you need further assistance. Thanks!

**Comment by rjhernandez** [comment]
Thanks for the info @raldaba, I got to say, I am really disappointed in the limitations of this tool.  Is there anywhere else where I can drop feature suggestions, or maybe even contribute code for this tool?
