### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by ruaandeysel** [microsoft/startstopv2-deployments#47]
Hi,

I deployed the new Start Stop v2 solution.

Any ideas why the dashboard don't work / populate with data?

Thanks.
![Screen Shot 2022-01-27 at 2 20 08 pm](https://user-images.githubusercontent.com/57021511/151291517-80b71a2b-caf4-4d33-bfa7-580aed7559fe.png)

**Comment by raldaba** [comment]
Hi @ruaandeysel Yeah, some things we can try out:
 
 - Do you have any successful start or stop operations going on? (To diagnose if the deployment was successful or if there's a more intrinsic issue going on)
 
 -Have you installed the latest bits of the SSV2 solution, and if so, can you confirm this installation is current?

Adding @balas77 for anything else I might have missed

**Comment by ruaandeysel** [comment]
Hi @raldaba, I managed to figure out the issue. My adblocker was blocking the azure monitor and application insights urls. Once I whitelisted the urls I could see the dashboard statistics.

**Comment by ericqms** [comment]
Awesome!

Thanks for getting back to us with the resolution so we can add it to our knowledge base in case other customers have the issue.

Eric Q.

**Comment by ruaandeysel** [comment]
Here's the URLs I added to custom allow list on adblocker

api.loganalytics.io
js.monitor.azure.com
api.applicationinsights.azure.com
api.applicationinsights.io
breeze.aimon.applicationinsights.io

**Comment by ericqms** [comment]
Appreciate it!
