### ISSUE TITLE
deploy into premium service plan (enhancement)

### ISSUE THREAD

**Issue by mathiaswegner** [microsoft/startstopv2-deployments#49]
I have an enhancement that I would like to see.

It would be nice if we could deploy the function app into a premium service plan so that we could limit network access to the storage account to a vnet rather than leaving it internet facing.

Deploying the function app into a premium service plan would allow us to deploy this solution and still follow the Defender recommendation of limiting network access to storage accounts.   If any credentials are compromised, having storage account access limited to a vnet would give us another layer of protection.

**Comment by balas77** [comment]
@mathiaswegner - Thanks for reaching us on this. Currently our SSV2 deployment scenario doesn't allow to choose the premium plan. You can change it after the deployment via Azure CLI. Check this [link ](https://demiliani.com/2020/12/02/moving-azure-functions-from-consumption-to-premium-plans/)and follow step 1 & 2 to move to premium plan.

**Comment by balas77** [comment]
Please feel free to reopen if you have any questions!
