### ISSUE TITLE
Scheduled start and stop not working on our subscription (error 400)

### ISSUE THREAD

**Issue by sebigut** [microsoft/startstopv2-deployments#50]
Hi! Im trying to use Start/Stop in 2 VMs we have in our subscription. However, it does not seem to be working. 

It gives 400 bad request whenever it tries to execute the function
This is the error that appears, both in ScheduledStop and ScheduledStart
> {
  "Message": "An error has occurred.",
  "ExceptionMessage": "Response status code does not indicate success: 400 (Bad Request).",
  "ExceptionType": "System.Net.Http.HttpRequestException",
  "StackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionClassicVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 149\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionVirtualMachinesAsync(String subscriptionId, Boolean classicEnabled) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 96\r\n   at StartStopAzureFunctions.BusinessLogic.UserRequestTranslatorBL.GetAccessibleVmsForSubscriptionScopesAsync(IEnumerable`1 subscriptionIds, Boolean classicEnabled) in D:\\a\\1\\s\\StartStopAzureFunctions\\BusinessLogic\\UserRequestTranslatorBL.cs:line 70\r\n   at StartStopAzureFunctions.Workflows.VirtualMachineScheduledRequestWorkflow.StartWorkflowAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\Workflows\\VirtualMachineScheduledRequestWorkflow.cs:line 83\r\n   at StartStopAzureFunctions.ScheduledRequestFunction.RunAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\ScheduledRequestFunction.cs:line 32"
}

**Things I checked/tried:**
- Checked that the function has collaborator permissions on the subscription and in the VMs. 
- Redeploying the solution
- Changing the scope of the function: I tried both trying to start and stop the whole subscription, and also tried to specify the 2 VMs. In both cases it fails in the same way.

Let me know if there is anything else I can share with you.

**Comment by balas77** [comment]
@sebigut - Sorry to hear on the error that you are facing. From the exception message I see that you are trying to take action on azure classic VMs. Before taking action on classic VMs, you have to make sure you set this property to true (**"EnableClassic": true**) in the Logic App payload. Also please make sure that you have enabled the **Microsoft.ClassicCompute** resource provider in that subscription. 

![image](https://user-images.githubusercontent.com/64924532/157137536-f5498528-21e3-491c-81e9-3b865685e4d0.png)

Can you please share the current payload that you are using in your logic app? It will be helpful for us to validate the payload schema. You can also share this to our internal emailid startstopv2team@microsoft.com

**Comment by sebigut** [comment]
Balas, thank you for the quick answer. The property EnableClassic is true as you say.

However, I cant find Microsoft.ClassicCompute resource provider in the subscription. It does not show up, neither registered nor unregistered.

I tried to enable it using Azure powershell CLI but it cant find it

**Comment by balas77** [comment]
is that subscription part of CSP program? Btw are you trying to start and stop the classic VMs?

**Comment by sebigut** [comment]
- Yes, we are using our subscription through CSP

- Yes, we are trying to start and stop classic VMs

**Comment by balas77** [comment]
CSP subscription doesn't support classic VMs. Are you saying that you already have classic VMs in that subscription?

**Comment by sebigut** [comment]
Yeah, we do. However, just as a FYI, the subscription became CSP after thoses VMs were already deployed. Could that be possible?

My company is from Argentina, and because of difficulties for paying for subscriptions in dollar, we instead started using a local provider as intermediary (I presume this is CSP)

**Comment by sebigut** [comment]
Ok, my mistake, the VMs resource property appears as Microsoft.Compute and not Microsoft.ClassicCompute. I may be confused about this point. I will try putting false in the EnableClassic Property and come back to you with an update

**Comment by sebigut** [comment]
Ok. I just tried executing it with **"EnableClassic": false** and it totally worked!

I feel really dumb now haha. Thank you so much, you were very helpful!

**Comment by datalytics1** [comment]
I just want to give thanks for this issue to exits. I had the same issue and now I know what was wrong. I think this happen because if you follow the guide that is posted from the official site of Microsoft you fall into this issue. They should have a place where they explain all the parameteres used on the configuration of this.
