### ISSUE TITLE
Looking for Monthly occurrence scheduling options.  Every 3rd Saturday etc..

### ISSUE THREAD

**Issue by ISI-kgozdzik** [microsoft/startstopv2-deployments#51]
Hi, I have fully deployed the Start/Stop VMs during off-hours overview (V2) solution in my environment.  However I am not seeing any options for properly scheduling a monthly start stop occurrence.  The options seems to be greatly limited.  I'm only seeing an option to select a particular number value (say the 17th of each month) rather than say the 3rd or 4th Saturday of each month.  Is there any option for this?  Also if we need to schedule a start stop within less than 24 hours I'm not seeing a method to create a single occurrence.  Is there any way to schedule a single occurrence (say I need to schedule a start/stop to run within next 4 hours)?  The only way I'm seeing now is to manually trigger the start/stop logical app.  I have also looked into trying to trigger the logical app using a scheduled task via PowerShell but have not been able to figure out how to get it to trigger automatically.  Please note, I have a lot of PowerShell programming knowledge.  I'm using the sequence start/stop (using tags) and this is working great.  I'm only having issues with the scheduling.

**Comment by balas77** [comment]
@ISI-kgozdzik - Thanks for using Start/Stop V2 solution. Currently we don't have much flexibility to customize the existing functionality of recurrence task. You can certainly reach Azure logic app support via portal to get further inputs on this.

Below are few links to check on the Logic apps recurrence task.

[Example 1](https://docs.microsoft.com/en-us/azure/connectors/connectors-native-recurrence#add-the-recurrence-trigger)

[Example 2](https://docs.microsoft.com/en-us/azure/logic-apps/concepts-schedule-automated-recurring-tasks-workflows#schedule-triggers)

**Comment by balas77** [comment]
Closing this for now and please reach out if you need further assistance
