### ISSUE TITLE
minimum permissions for cross subscription

### ISSUE THREAD

**Issue by ajpogue** [microsoft/startstopv2-deployments#52]
Hi!  What is the minimum permission for cross subscription use? Contributor seems too much.

**Comment by balas77** [comment]
@ajpogue - You can certainly use "Virtual Machine Contributor" role but that will work only for Scheduled/Sequenced scenarios. If you plan to use our AutoStop scenario then it needs "Contributor" role.

**Comment by balas77** [comment]
If there's no further action, then I will close this ticket now.
