### ISSUE TITLE
Please update documentation for support. 

### ISSUE THREAD

**Issue by ajpogue** [microsoft/startstopv2-deployments#53]
Hello!  Could you update whichever is incorrect below, please?

I see on the Troubleshooting page, https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/troubleshoot, under Next Steps:
If you run into problems during deployment, you encounter an issue when using Start/Stop VMs v2 (preview), or if you have a related question, you can submit an issue on [GitHub](https://github.com/microsoft/startstopv2-deployments/issues). **Filing an Azure support incident from the [Azure support site](https://azure.microsoft.com/support/options/) is not available for this preview version.**

On the github page, https://github.com/microsoft/startstopv2-deployments#customer-support-contact, you say to open a Support case. 

Thank You!

**Comment by balas77** [comment]
Public doc updated, hence closing this issue.
