### ISSUE TITLE
Question re: Sequence delays

### ISSUE THREAD

**Issue by JJCrofts** [microsoft/startstopv2-deployments#56]
With previous start/stop runbooks we had to build in a delay between starting a SQL database VM and starting associated apps - time to allow SQL to properly start up.  In testing starting a couple of VMs in sequence with StartStopV2, it seems that the 2nd VM doesn't begin to start until the 1st VM has completely started... but that could be coincidence.

Can anybody explain the logic of the sequencing in this case? Does it wait for the previous VM to be fully started (maybe the Azure Agent is up, etc?) before moving on to the next?

If not, short of having multiple functions to start the database then pause, is there a way to include a delay such as this in the main request body of the start action?

Thanks

**Comment by balas77** [comment]
@JJCrofts - In our V1 solution, we have the variable WaitTime_ which is used to hold the retry time until the VM is in a running state and the execution will move on to the next VM in the sequence. We don't have any flexibility to pause/hold even after the VM has reached a running state.

This is mostly the same behavior in our V2 solution where the 2nd VM execution will start once the prior VM state has been reached. As mentioned above, we will wait until the VM has reached a running state before performing the 2nd VM in order. It does not wait for any other services like what you have mentioned to run in that VM. Ideally, this is called "Delayed execution" and it's in our backlog and we will pick that up based on the priority.

**Comment by balas77** [comment]
@JJCrofts I am closing this ticket for now and please reopen if you have any questions!
