### ISSUE TITLE
autostopalertexecutor fail to create needed alert

### ISSUE THREAD

**Issue by krazy-glue** [microsoft/startstopv2-deployments#58]
I configured the autostartstopv2 app last week, the logic app for autostop was working correctly on 2022-06-10 but then the next day, the logic app queue report a badrequest with no more details.
I try to look for more details but none seems to be available.
I thought maybe the function app lost the permission to access the VM or the subscription everything looks fine.

**Comment by balas77** [comment]
@krazy-glue - Did something got changed in the logic app's payload? Can you share the payload to us via **startstopv2team@microsoft.com**? Bad request seems to be something wrong with the payload or some settings got changed in the function app.

**Comment by krazy-glue** [comment]
yeah, I made a change on the payload, I change the Time window and use an invalid option. I configured the default option and then the alert rules has been created.

thank you
