### ISSUE TITLE
Open sourcing code

### ISSUE THREAD

**Issue by matsest** [microsoft/startstopv2-deployments#6]
This looks like an interesting approach and I see that it's linked to in [MS Docs](https://docs.microsoft.com/en-us/azure/automation/automation-solution-vm-management).

Is there a particular reason why the source code is not open sourced? I see that the templates are available on the storage account, but the most important components for the functions are the DLLs, which are only available in compiled format.

**Comment by parojasmsft** [comment]
We are currently working through the review required by Microsoft for all open source item, once the review is complete it will allow us to share all source code for the project. In addition to Microsoft Docs, our product will be listed in Azure Marketplace for those that want to just deploy start/stop v2 to their subscription. We will however maintain version parity between changes made on github and Azure Marketplace.

**Comment by matsest** [comment]
Thanks @parojasmsft - looking forward to it!

**Comment by skmkzyk** [comment]
Could you please provide an update on the availability of the source code?

**Comment by jeffw16** [comment]
@skmkzyk Thank you for your inquiry. Our business priorities have shifted, and as a result, we are no longer planning to open source the code.
