### ISSUE TITLE
Dashboard shows no data

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/startstopv2-deployments#60]
"No data for the given query"
I use scheduled start/stops and it does start and stop VMs daily

**Comment by joaosaffran** [comment]
Hi @turbozapekanka, we have some closed issue that are similar to the one you are facing, please check those out:
- https://github.com/microsoft/startstopv2-deployments/issues/12
- https://github.com/microsoft/startstopv2-deployments/issues/47

If those don't work, please provide a more context on this issue, some screenshot or some logs if you have access to those.

FYI: @balas77

**Comment by ajvdburg** [comment]
Hi,

I installed the solution last week and also have the issue of not getting any data on the dashboard. It appears the prop_Value property is missing in de customDimensions AI property:

![image](https://user-images.githubusercontent.com/5416532/177722245-56060349-3095-4e00-8c0d-9a9fb6a64fcd.png)
![image](https://user-images.githubusercontent.com/5416532/177722315-e3aa3a13-d056-483f-9f62-d5c83fccc184.png)
![image](https://user-images.githubusercontent.com/5416532/177722545-1b7d0433-abac-4aaf-9bb4-33dc43e1cab1.png)

Kind regards,

Arnold Jan van der Burg

**Comment by alurbina** [comment]
Do you know if the VMs are being successfully started and stopped @ajvdburg ?

**Comment by ajvdburg** [comment]
@alurbina : yes once the log log apps were enabled the solution is working as expected

**Comment by svarga-msft** [comment]
Closing this as customer reported solution is working.
