### ISSUE TITLE
Expected Run Behavior (Initial Enable, Run From Trigger, Scheduling)

### ISSUE THREAD

**Issue by DylanMsft** [microsoft/startstopv2-deployments#63]
I saw a previous issue  https://github.com/microsoft/startstopv2-deployments/issues/35  where the final comment is that the default behavior is to run on the initial enable.  

I have tried this a few a times, but it does not run on the initial enable for me.  I also have a customer who says that normally it doesn't run when they do the initial enable but there are rare occasions when it does.

Since that issue is nearly a year old now, what is the current expected behavior?  Why are we seeing inconsistent results?

When I was testing, after the initial enable didn't trigger a run, I decided to do a run trigger in case that is what the customer did as well.  When I did that, the trigger ran twice.  This has happened each time, but subsequent runs of the trigger only happen once.

These seem like they could be somewhat related.  I am really just interested to find out what the expected behavior is.

We have also found that for a 1 week schedule the date can be that of the first run.  On a 4 week schedule, the date had to be set to 4 weeks prior.  Is this expected/intended as well?

**Comment by balas77** [comment]
@DylanMsft - The current behavior is still the same. When you enable the logic app, the workflow will get executed and this **will happen only the first time when you enable it** (just to get the recurrence schedule settings if you have this task in the workflow). Even today, I see this behavior when I perform some tests.  Many people are not expecting the first default run but that's how the behavior was confirmed from the logic app team who owns this.  As per your case, the execution happened twice, which means it ran for the default first run and another one for your manual run.

Here is the community discussion about the same ask https://docs.microsoft.com/en-us/answers/questions/881744/logic-app-triggered-immediately-after-enabling.html

**Comment by DylanMsft** [comment]
@balas77

Thanks for getting back to me.

>  As per your case, the execution happened twice, which means it ran for the default first run and another one for your manual run.

That makes sense in general but it still doesn't fit into what you said above:

> When you enable the logic app, the workflow will get executed

When I clicked enable, the workflow did not execute.  Nothing happened until I clicked "Run Trigger" at which point it ran twice.

**Comment by balas77** [comment]
@DylanMsft - As I said above, this will happen only once for the first time when you enable it, and this is the information shared by the logic app team since I don't own that functionality. Please feel free to reach out to the logic app support team to make sure on the expected behavior.

**Comment by balas77** [comment]
@DylanMsft - Please let me know if you have any additional questions!

Note: When you enable the logic app for the **first time**, the execution will happen (which is the default behavior) and you don't need to manually run the trigger. But rarely it will not immediately display in the execution history even after you click "refresh" button in the blade. Please make sure you refresh the browser page to see the execution.
