### ISSUE TITLE
Minimum TLS version on storage account created is Version 1.0

### ISSUE THREAD

**Issue by jbailey-limgeomatics** [microsoft/startstopv2-deployments#66]
When this solution is deployed to Azure, the minimum TLS version on the storage account created is Version 1.0. Best practice is to use TLS 1.2, and is the default on newly-created Azure storage accounts. Is there a reason why TLS 1.0 is the minimum version for this solution? Is there risk to updating to TLS 1.2?

**Comment by balas77** [comment]
@jbailey-limgeomatics - There is no risk in updating to TLS 1.2 and solution will work fine.

**Comment by tatsuyaHello** [comment]
@balas77 
Do you know when the TLS version included in this deployment template will be updated from 1.0 to 1.2?
