### ISSUE TITLE
Deployment over BICEP or JSON

### ISSUE THREAD

**Issue by philg1234** [microsoft/startstopv2-deployments#79]
Hello together,

is it possible to deploy this Solution over JSON oder BICEP with DevOps?

##

if it's not possible, would be a possibility to change the Names to the OWN Naming Schemes was very helpful...

Thanks a lot.

Best Regards,
Phil

**Comment by jeffw16** [comment]
Thank you Phil for your feedback. At this time, we do not have plans to support either.
