### ISSUE TITLE
The Deploy to Azure button is not working

### ISSUE THREAD

**Issue by neo475269** [microsoft/startstopv2-deployments#81]
When I clicked the "Deploy to Azure" button, I got the following error.  Any help?
![startstopv2error](https://user-images.githubusercontent.com/53286159/227099416-4cf61c79-347c-4f03-88c5-cc6ebacacbe7.png)

**Comment by balas77** [comment]
Should work. Did you tried to deploy from the azure marketplace?

**Comment by jeffw16** [comment]
This seems like an issue with the Azure portal. It is working for me.
