### ISSUE TITLE
"ResourceGroups" seems to be ignored

### ISSUE THREAD

**Issue by PrismaComputer** [microsoft/startstopv2-deployments#90]
The given resource group is completely ignored. Without any errors and/or other feedback.

**Behaviour:**
Every machine within this subscription, except 2 VMs, is started, which is not intended.

**Expected behaviour:**
Every machine within this resource group is started, except 2 VMs.

```json
{
  "Action": "start",
  "EnableClassic": false,
  "RequestScopes": {
    "ExcludedVMLists": [
      "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/DEFAULT-STORAGE-WESTEUROPE/providers/Microsoft.Compute/virtualMachines/VM01",
      "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/DEFAULT-STORAGE-WESTEUROPE/providers/Microsoft.Compute/virtualMachines/VM08"
    ],
    "ResourceGroups": [
      "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/Default-Storage-WestEurope/"
    ],
    "Subscriptions": [
      "/subscriptions/11111111-2222-3333-4444-555555555555/"
    ]
  }
}
```

Maybe a bug, maybe not. The documentation regarding this is very thin. Not clear what to expect and how to configure the expected.

**Comment by gatti2602** [comment]
Hit the same issue today, ResourceGroup got completely ignored and all the machines in the subscription got affected. 

As per docs in [here](https://learn.microsoft.com/en-us/azure/azure-functions/start-stop-vms/deploy), this should work: 

> In the request body, if you want to manage VMs for specific resource groups, modify the request body as shown in the following example. Each resource path specified must be separated by a comma. You can specify one resource group or more if required.
> 
> This example also demonstrates excluding a virtual machine. You can exclude the VM by specifying the VMs resource path or by wildcard.
```
{
  "Action": "start",
  "EnableClassic": false,
  "RequestScopes": {
    "Subscriptions": [
      "/subscriptions/12345678-1234-5678-1234-123456781234/",
      "/subscriptions/11111111-0000-1111-2222-444444444444/"
     ],
    "ResourceGroups": [
      "/subscriptions/12345678-1234-5678-1234-123456781234/resourceGroups/rg1/",
      "/subscriptions/11111111-0000-1111-2222-444444444444/resourceGroups/rg2/"
    ],
    "ExcludedVMLists": [
     "/subscriptions/12345678-1234-5678-1234-123456781234/resourceGroups/vmrg1/providers/Microsoft.Compute/virtualMachines/vm1"
    ]
  }
}
```

**Comment by PrismaComputer** [comment]
Dear gatti2602,

thank you for your answer. Glad (and sad the same time) that you hit the same problem. So it seems to be not on us.
Are holidays in the US, or why is nobody from MS answering this thread?

**Comment by dinvlad** [comment]
> Are holidays in the US
There's Microsoft Build conference this week, which might explain some of this, but judging by lack of recent commits or answers to other issues, I'd hazard a guess that there's no longer a person assigned to it, sadly.

**Comment by PrismaComputer** [comment]
OK, I found a solution, or better an explanation. The main misunderstanding seems to come from a bad documentation and partially not working examples. Maybe it's also unintended behaviour of the function app. But we will never know, nobody is answering here.

Explanation:
"ResourceGroups" and "Subscriptions" **logically expand** "RequestScopes", they do **not limit** the scope. Means:
* If you name a subscription in "Subscriptions", all VMs in the subscription are targeted. Despite single named VMs or resource groups.
* If you name a resource group in "ResourceGroups", all VMs in the Resource group are targeted. Despite single named resource groups.

Leaving "Subscriptions" blank or out, solved my problem:

```json
{
  "Action": "start",
  "EnableClassic": false,
  "RequestScopes": {
    "ExcludedVMLists": [
      "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/DEFAULT-STORAGE-WESTEUROPE/providers/Microsoft.Compute/virtualMachines/VM01",
      "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/DEFAULT-STORAGE-WESTEUROPE/providers/Microsoft.Compute/virtualMachines/VM08"
    ],
    "ResourceGroups": [
      "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/Default-Storage-WestEurope/"
    ]
  }
}
```
